### ISSUE TITLE
Feature-Request: Ebics für Lastschriften

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#106]
Ich habe lange nachgedacht ob ich diesen Request schreiben soll, weil er doch sehr speziell ist. Ich weiß auch nicht ob es noch andere Anwender gibt die dieses Feature brauchen könnten. Nur dann macht es auch Sinn, Aufwand für ein solches Feature zu spendieren. Aber vielleicht ergibt sich eine Diskussion und es melden sich noch mehr.
Ich habe bereits in alten Diskussionen in Hibiskus gelesen, dass ein Ebics Support in Hibiskus keinen Sinn macht. Das kann ich gut verstehen. Ebics ist ja mehr für Firmen gedacht und die können sich auch kommerzielle Tools für das Banking leisten. Ich rede hier also nicht von Hibiscus sondern nur von JVerein und nur Lastschrift.
Woher kommt also der Request?
Ich verwalte einen kleinen Verein und nutze JVerein. Wir haben das Konto bei der Sparda-Bank München. Bankgeschäfte mache ich mit Hibiscus und JVerein über HBCI. Leider unterstützt die Bank aber keine Lastschriften über HBCI. Für Lastschriften habe ich einen Ebics Zugang für das gleiche Konto bekommen. Ich ziehe einmal im Jahr Lastschriften ein. Dazu generiere ich in JVerein die XML Datei und schicke sie mit Starmoney Business, welche ich von meinem Vorgänger habe, an die Bank. Starmoney Business verwende ich also nur einmal im Jahr um die Datei zu senden.
Natürlich ist das kein größerer Aufwand, aber schöner wäre es natürlich, ich könnte die Datei direkt aus JVerein verschicken.
Man brächte also wohl in der Implementierung den initialen Handshake zum Austausch der Schlüssel um das Konto einzurichten und den Support für Lastschriften. Ich weiß jetzt nicht wie aufwändig das ist.
Ich habe gesehen, dass es auf https://github.com/ebics-java/ebics-java-client einen Ebics Client gibt auf den man aufsetzen könnte. Er wird aber auch schon länger nicht gepflegt und unterstützt wohl nicht die neuesten Versionen 3.x.
Wie gesagt, das ist nur ein Vorschlag um herauszufinden ob noch andere User ein solches Problem haben bzw. ob es noch andere Banken gibt die über HBCI keine Lastschriften unterstützen.
Rege Antworten sind willkommen.

**Comment by willuhn** [comment]
Bist du sicher, dass deine Sparda-Bank das nich kann? Die hängen doch an einem gemeinsamen Rechenzentrum, welches das eigentlich unterstützen sollte. Hast du mal getestet, die Aufträge als Sammellastschrift zu senden - auch wenn jeweils nur eine Buchung enthalten ist? Viele Banken unterstützen per FinTS nur Sammellastschriften aber keine Einzellastschriften.

**Comment by JohannMaierhofer** [comment]
Als ich die Aufgabe von meinem Vorgänger übernommen habe, habe ich die Bank gefragt ob ich die Lastschriften über HBCI machen kann. Sie sagten mir, das das nicht geht und ich einen EBICS Zugang verwenden muss. Ich kann aber natürlich mal probieren was passiert wenn ich das über HBCI versuche.

**Comment by willuhn** [comment]
Für das Einreichen von Lastschriften brauchst du in aller Regel eine Vereinbarung mit der Bank. "Einfach so" wird das also vermutlich auch mit Sammellastschriften nicht funktionieren (wobei du es durchaus mal testen kannst). 

Du kannst aber mal in den BPD schauen, ob es die Bank grundsätzlich kann - unabhängig davon, ob es bei dir freigeschaltet ist oder nicht. Öffne hierzu den Bankzugang in Hibiscus, klicke unten auf "BPD/UPD" und gib als Suchbegriff "SammelLastSEPA" ein. Wenn da nichts kommt, kann die Bank das in der Tat nicht.

**Comment by JohannMaierhofer** [comment]
Da kommt nichts.

**Comment by willuhn** [comment]
Dann kann es die Bank tatsächlich nicht und du brauchst auch nicht testen.
Ich persönlich würde dir empfehlen, dafür einfach ein zweites Vereinskonto bei einer anderen Bank einzurichten, die das kann. Das wäre deutlich weniger Aufwand als die Implementierung der EBICS-Anbindung. Die meisten Banken können eigentlich Sammellastschriften per FinTS.

**Comment by JohannMaierhofer** [comment]
Ja, ein Wechsel der Bank wäre auch eine Lösung. Ich habe mich da auch schon mal bei der Skat-Bank erkundigt. Die bieten ja kostenlose Konten für Vereine. Die hatten aber das Problem, dass ich erst einmal nur sehr kleine Summen einziehen dürfte. Sie begründeten das, dass es ja ein Kredit sei und das Risiko besteht, dass die Lastschriften wieder zurückgerufen werden. Erst wenn wir länger bekannt sind könnte ich mehr einziehen. Damit war das nicht brauchbar.
Aber ich kann ja noch weiter schauen.
Danke für die Rückmeldungen.
