### ISSUE TITLE
Kontoauszug Zuordnung sortiert Buchungsliste um

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#110]
Warum wird in der BuchungKontoauszugZuordnungAction.java bei der Änderung von Auszugs- und Blattnummer eine BuchungMessage verschickt?
Bei anderen Änderungen wie z.B. in BuchungMitgliedsKontoZuordnungAction oder BuchungProjektZuordnungAction nicht.
Diese Implementierung führt dazu, dass die Buchungsliste umsortiert wird. Ich habe sie so sortiert, dass die neuesten Buchungen oben sind. Setzt man den Kontoauszug wird die Liste umsortiert und die ältesten sind oben.
Das ist unschön weil der gerade editierte Eintrag erst einmal verschwindet und man explizit neu sortieren muss.
Geht das auch ohne die Sortierung zu ändern bzw. ist das verschicken nötig?

**Comment by JohannMaierhofer** [comment]
Also ich sehe kein Fehlverhalten wenn man 
Application.getMessagingFactory().sendMessage(new BuchungMessage(buchung));
entfernt.
Kann ich das machen?

**Comment by MSchmalzl** [comment]
Kann meiner Meinung nach entfernt werden.

**Comment by MSchmalzl** [comment]
Erledigt mit #113.
