### ISSUE TITLE
QR code for online payment

### ISSUE THREAD

**Issue by haudi31** [openjverein/jverein#151]
Would be nice to have a QR code for online payment on the Bill with the amount (best the member fee or the "open" fee) and the member number/external number in the reference field. Also as text would be good. Beste the name of the fee (member fee 2024).

**Comment by SchachtnerTh** [comment]
Hallo zusammen,
bitte versteht mich nicht falsch, ich werde das wahrscheinlich nicht hinkriegen, aber ich bin gerade dabei, mit dem Sourceode zu spielen. Zum Beispiel dachte ich, ich hätte es geschafft, einen Konfigurationsschalter bei den Rechnungseinstellungen einzubauen, der angibt, ob ein QR-Code gedruckt werden soll oder nicht.
Beim Speichern wird mir eine Fehlermeldung angezeigt, dass eine Spalte in der Tabelle fehlt.
Meine Vermutung ist, dass für jede Einstellung eine eigene Spalte in der Datenbank benötigt wird.
Da ich eine neue Einstellung gemacht habe, ist in der Datenbank noch keine solche Spalte.

So, jetzt meine Fragen:
- Ist es gewollt, dass in der Datenbank neue Spalten hinzugefügt werden?
- Wenn ja, wie geht das?
- Angenommen, ich habe das lokal bei mir gemacht: Dann ist das Feld ja bei allen anderen Installationen noch nicht verfügbar. Wie krieg ich hin, dass das Feld auch bei den bestehenden Installationen bei einem Update angelegt wird?

Viele Fragen. Aber ich bin hier neu und ich würd das schon gerne lernen und verstehen.
Hat denn jemand die Geduld, mir das kurz zu erklären?

LG
Tom

**Comment by SchachtnerTh** [comment]
Hallo,
ich hab jetzt ein bisschen rumgespielt und es tatsächlich geschafft, einen QR-Code zu erzeugen, den man als Formularfeld auf der Rechnung platzieren kann.
Ich bin mir aber nicht sicher, ob das so passt, ob ich irgendwas Wichtiges vergessen habe oder ob ich prinzipiell auf dem richtigen Weg bin.

Kann sich das [hier](https://github.com/SchachtnerTh/jverein/tree/QR_Code_as_form_element) mal wer anschauen?

Für einen Pull-Request ist es wahrscheinlich noch ein bisschen früh, denke ich... (außedem hab ich das noch nie gemacht ;-))

LG Tom

**Comment by SchachtnerTh** [comment]
>     1. Bitte den .settings Ordner in deine .gitignore aufnehmen (da keiner deine persönlichen Einstellungen benötigt).

Wenn ich den .settings-Ordner in meine .gitignore eintrage, werden plötzlich alle Dateien als UTF-8 abgespeichert und die Umlaute werden falsch angezeigt.
Im master-Branch ist dieser Ordner auch enthalten.

... und schon steck ich wieder fest ;-)

**Comment by SchachtnerTh** [comment]
Ist das Problem damit behoben?
Oder fehlt noch was?

**Comment by MSchmalzl** [comment]
Ist mit PR #205 erledigt.
