### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by mbmueller** [openjverein/jverein#173]
In einigen Klassen werden Umlaute verwendet. Dies führt in meiner IDE zu Problem mit dem Encoding. Generell sind Sonderzeichen in Code eher Bad Practice, schlage daher vor die zu entfernen.

**Comment by willuhn** [comment]
Hast du mal ein Beispiel in einer konkreten Datei? Und hast du das korrekte Encoding eingestellt? JVerein verwendet ISO-8859-1 (nicht UTF-8).

**Comment by mbmueller** [comment]
Außerdem ist mir aufgefallen, dass das an manchen Stellen im Code eh schon als ae gehandhabt wird und daher inkonsistent ist.

**Comment by willuhn** [comment]
Dann musst du in IntelliJ eine Option suchen, mit der man das Encoding des Projekts manuell vorgeben kann. Das muss in einer vernünftigen IDE doch konfigurierbar sein.

**Comment by willuhn** [comment]
> Außerdem ist mir aufgefallen, dass das an manchen Stellen im Code eh schon als ae gehandhabt wird und daher inkonsistent ist.

Solange sich das auf Kommentare im Quellcode bezieht, ist das egal. Relevant sind nur die Stellen, in denen Text in der Anwendung auch angezeigt wird.

**Comment by mbmueller** [comment]
Mein Problem sind nicht in Kommentaren bzw. String Literals.
Mein Problem liegt im Code. In den Strings passt alles mit dem Encoding. Aber IntelliJ lässt bei mir keine Nicht-ASCII Zeichen in ausführbaren code zu.

**Comment by willuhn** [comment]
Poste doch mal ein Beispiel.

**Comment by mbmueller** [comment]
junit/src/de/jost_net/JVereinJUnit/io/SuchbetragTest.java Zeile 68: GRÖSSER

**Comment by willuhn** [comment]
Wird bei mir in Eclipse fehlerfrei angezeigt:

![image](https://github.com/openjverein/jverein/assets/956215/ea0733ae-d442-434e-8ff1-6f0a393997db)

**Comment by mbmueller** [comment]
Das Problem ist auch nicht das Anzeigen in der IDE, sondern das mir der Compiler beim Builden fehlschlägt wegen nicht-zugelassener Zeichen

**Comment by mbmueller** [comment]
Deswegen ist das in Strings und Kommentaren auch kein Problem, da kann der damit umgehen, nur im Code selber eben nicht.

**Comment by willuhn** [comment]
> Das Problem ist auch nicht das Anzeigen in der IDE, sondern das mir der Compiler beim Builden fehlschlägt wegen nicht-zugelassener Zeichen

Beim Compilieren muss halt angegeben sein, mit welchem Encoding der Compiler den Source zu lesen hat. Im Ant-Script passiert das auch. Wenn es nicht explizit angegeben ist, wird i.d.R. das Plattform-Encoding verwendet, welches in deinem Fall dann halt falsche sein kann.

**Comment by mbmueller** [comment]
Alles klar habs jetzt geändert. Finde das dennoch irgendwie nicht gut gemacht Sonderzeichen im Code zu verwenden.

**Comment by mbmueller** [comment]
Kurze Frage am Rande: Jetzt sagt der Compiler, dass de.jost_net.OBanToo fehlt. Hast du dazu auch ne Lösung??

**Comment by willuhn** [comment]
Die Klasse befindet sich in Hibiscus in "hibiscus/lib/obantoo-bin-2.1.12.jar". JVerein hat eine Projektabhängigkeit zu Hibiscus.

**Comment by willuhn** [comment]
Wenn man JVerein in Eclipse öffnet, ist das auch passend konfiguriert in https://github.com/openjverein/jverein/blob/master/.classpath#L9

**Comment by mbmueller** [comment]
Alles klar, danke. Mal schauen ob und wie ich das dann bei mir fixe, würde halt gerne bei IntelliJ bleiben.
