### ISSUE TITLE
[Feature] Kontensaldo mit frei wählbarem Zeitraum

### ISSUE THREAD

**Issue by dominformant** [openjverein/jverein#175]
Aktuell bietet JVerein nur jährliche Kontensalden an. Gerade in Hinblick auf Zwischenprüfungen der Kasse wäre es jedoch praktisch diese mit frei wählbarem Zeitraum anzeigen zu können, so wie es bei den Buchungsklassensalden auch möglich ist.

**Comment by JohannMaierhofer** [comment]
Ja, das habe ich mir auch gewünscht und bereits implementiert, aber auf Basis des #167. Sobald dieser übernommen ist werde ich einen Pull Request dafür erstellen.
Und wie du schon schreibst habe ich da den Namen Jahressaldo in Kontensaldo umbenannt.

**Comment by dominformant** [comment]
Oh, super, vielen Dank für deine Arbeit an dem Projekt, bzw. natürlich auch die der anderen Beitragenden.

**Comment by MSchmalzl** [comment]
Umgesetzt mit #180.
