### ISSUE TITLE
Spendenbescheinigungen per Mail versenden

### ISSUE THREAD

**Issue by SchachtnerTh** [openjverein/jverein#191]
Was würdet ihr davon halten, wenn es eine Funktion gäbe, die bei Leuten, bei denen eine E-Mail-Adresse hinterlegt ist, die Zuwendungsbestätigung direkt als Mail verschickt werden könnte?
Vielleicht auch noch mit einer schönen Vorlage, dass da auch ein bisschen Text und Formatierung mit dabei ist. Dann wäre das auch etwas ansprechend.
Ich denke, dass eine händische Unterschrift für die Zuwendungsbestätigungen nicht unbedingt notwendig ist.
Was haltet ihr davon?

**Comment by JohannMaierhofer** [comment]
Ja, das würde mir auch gefallen. Das könnte man so ähnlich machen wie bei der Pre-Notification.
Für das Finanzamt braucht man die Unterschrift. Aber da man heute keine Unterlagen mehr einreichen muss wäre das ja auch ohne ok.
Wenn dann jemand die Unterschrift braucht, kann man dem ja dann immer noch die Bescheinigung in Papierform schicken.

Ich habe mir gerade einige meiner Spendenbescheinigungen angeschaut. Da sind die Unterschriften gedruckt. Das könnte auch ein Feature für Jverein sein.
Man macht eine Unterschrift auf weißes Papier und macht dann ein Foto oder scannt es ein. In den Einstellungen könnte man dann das Bild in Jverein laden und beim generieren der Bescheinigung an die richtige Stelle im PDF drucken.

**Comment by SchachtnerTh** [comment]
Sehr viele Bescheinigungen, die ich kriege, haben nur eine gedruckte Unterschrift. Ich glaube, das wäre überhaupt kein Problem, wenn die Unterschrift entweder hinzugefügt wird oder bereits in der verwendeten Vorlage enthalten ist.

**Comment by JohannMaierhofer** [comment]
Ich werde versuchen eine gedruckte Unterschrift für die Standard Spendenbescheinigung zu implementieren.
Die Idee ist, in den Einstellungen ein Bild der Unterschrift zu laden und diese dann falls gewünscht in die automatisch generierte Spendenbescheinigung einzufügen.

**Comment by SchachtnerTh** [comment]
Ich hätte vermutlich die Unterschrift gleich fest auf die Vorlage gedruckt und nur die beweglichen Teile des Formulars als Formularfelder implementiert. Ich glaube, wir bräuchten dieses Feature der konfigurierbaren und positionierbaren Unterschrift nicht unbedingt im Verein. Ist aber vielleicht für Vereine interessant, die teilweise Spendenbescheinigungen voll-digital erzeugen und teilweise den Ausdruck unterschreiben und nicht zwei unterschiedliche Formulare verwenden wollen?

**Comment by JohannMaierhofer** [comment]
Ich erzeuge meine Spendenbescheinigungen alle automatisch ohne Vorlage. Da brauche ich diese Möglichkeit.

**Comment by JohannMaierhofer** [comment]
@SchachtnerTh , @dippeal , @MSchmalzl 
Ich habe gerade das Versenden der Spendenbescheinigungen implementiert. Es funktioniert soweit. Hängt aber noch von #211 ab.
Ich habe allerdings ein Problem, welches ich mit euch besprechen möchte. Der Mail Anhang (Spendenbecheinigung) wird beim versenden in der Datenbank gespeichert. Zumindest war das so üblich, damit man die Mails später ansehen kann und evtl. nochmals versenden kann.
Der Filename für Anhang ist in der Datenbank aber auf 50 Zeichen beschränkt. Mein Filename für die Spendenbescheinigung war aber länger. Zwar wurde nun die Mail versendet aber der Anhang nicht gespeichert.
Wie wollen wir das lösen?
- Den Default Namen für Spendenbescheinigung kürzen z.B. Spendenbescheinigung mit Spb abkürzen, wird aber wohl nicht reichen
- Die Länge in der Datenbank auf z.B. 100 Zeichen vergrößern

Ein anderer Weg wäre noch, die Mails für den Versand der Spendenbescheinigungen überhaupt nicht in der Datenbank zu speichern. Da werden dann ja doch im Laufe der Zeit sehr viele Dokumente gespeichert.
Wenn man die Bescheinigung später wieder senden will kann das ja auch so leicht machen wenn man den Menüpunkt zum Versenden erneut aufruft.

Meine Implementierung würde so aussehen:
Ein neuer Menüpunkt bei Spendenbescheinigungen, multi Selection ist aktiv:
![Screenshot_20240418_170901](https://github.com/openjverein/jverein/assets/126261667/6c2214a0-580c-4a78-8b24-c35b3200397f)
Dann kommt ein Dialog wo man entscheiden kann ob die Spendenbescheinigungen gedruckt werden sollen. Sind sie schon gedruckt kann man ohne neues drucken weiter gehen.
![Screenshot_20240418_171915](https://github.com/openjverein/jverein/assets/126261667/e3f39d4a-c099-4da3-9d8a-e6b25592efbc)
Der View zum senden schaut dann so aus. Im Info Feld liste ich Mitglieder auf die keine Mailadresse haben. Für die muss man dann halt die Bescheinigungen per Brief versenden.

![Screenshot_20240418_171105](https://github.com/openjverein/jverein/assets/126261667/ce7999bf-a0f6-46d7-81a4-25cc06f2c5c2)

**Comment by SchachtnerTh** [comment]
Ich hatte leider noch keine Zeit, mir Deine Implementierung anzuschauen und weiß auch nicht auswendig, wie das aktuell in JVerein gelöst ist, aber ich bin auch der Ansicht, dass die Spendenbescheinigungen nicht in die Datenbank müssen.
Sie sollten aber auf jeden Fall als Datei in einem Verzeichnis liegen und dort bleiben.

So, wie ich das sehe, ist bei Dir aber der Druck beim ersten Versenden sowieso verpflichtend. Vermutlich, weil da die PDF-Datei erzeugt wird. Für mich wäre das ausreichend so.

Je nachdem, wie ich die Spendenbescheinigungen versende und wie ich meine Maileinstellungen konfiguriert habe, habe ich ja vielleicht auch in den gesendeten Objekten das Mail mit Anhang.

Ist aber nur meine Ansicht.

**Comment by JohannMaierhofer** [comment]
Ja, man muss sie auf jeden Fall drucken. Entweder hat an das schon vorab mit den entsprechenden Menüpunkten gemacht oder man macht das jetzt beim versenden. Sie werden dann als Attachment an die Mail gehängt. 
Also hat an ja die PDFs welche man sowieso 10 Jahre aufbewahren muss.
Damit denke ich auch, dass man sie dann nicht doppelt speichern muss.
Die Frage wäre dann noch, ob man die Mails ohne Anhang in der DB speichert oder ob mann sie gar nicht speichert. Wahrscheinlich dient das Speichern zur Dokumentation der erfolgten Kommunikation.

**Comment by SchachtnerTh** [comment]
so sehe ich das auch.
Speichern: ja, Anlage: nein.
Ist es möglich, irgendwie zu kennzeichnen, dass es einen Anhang gegeben hat, der aber entfernt wurde?
Ich glaube zwar nicht, dass es unbedingt notwendig ist, aber der Anwender sollte schon wissen, dass die Anhänge entfernt wurden. Wenn ich das richtig verstehe, werden andere Anhänge ja in die Datenbank geschrieben. Das kann schon verwirren...
Vielleicht wäre eine Option gut, mit der man angeben kann, ob die Spendenbescheinigungen, die per Mail versandt werden, in der Datenbank gespeichert werden sollen?

**Comment by JohannMaierhofer** [comment]
Ich hatte auch schon die Idee eines Schalters. Ich werde das dann so machen. Dann muss ich aber auch die Länge des Dateinamen in der DB vergrößern.
