### ISSUE TITLE
Buchungsliste: Filter auf Betrag vorzeichenlos

### ISSUE THREAD

**Issue by JPT77** [openjverein/jverein#194]
Vorschlag einer kleinen Änderung: 
der Betrag sollte vorzeichenlos sein, also jeweils alle Einträge finden, die diesen Betrag haben, egal ob positiv oder negativ.

Möglicherweise im Umfeld von dem hier?

    de.jost_net.JVerein.gui.control.BuchungsControl.getSuchBetrag()
    de.jost_net.JVerein.gui.control.BuchungsControl.getBuchungsList()

dankeschön

**Comment by JPT77** [comment]
Evtl auch runden? damit man die Centbeträge nicht eingeben muss?
oder Runden wenn keine Centbeträge angegeben sind?

**Comment by JohannMaierhofer** [comment]
Was ist denn der Anwendungsfall für diesen Request?
Ich verstehe das nicht ganz, wenn ich etwas suche, möchte ich doch das bekommen wonach ich suche und nicht noch etwas anderes.

**Comment by mbmueller** [comment]
Das mit dem Vorzeichen kann ich verstehen, das Problem beim Runden ist, dass es mathematisch mindestens 3 Methoden gibt zu Runden, die alle korrekt sind. Die Frage wäre dann wie man hierbei rundet. Sollen also nur die Centbeträge abgeschnitten werden oder was soll genau passieren? Hierbei wäre eventuell sinnvoll, dass man einen Bereich angeben kann.

**Comment by JohannMaierhofer** [comment]
Das mit dem Runden verstehe ich auch.
Das mit dem Vorzeichen finde ich persönlich nicht so gut. Könnte man man diese Option über die Einstellungen konfigurierbar machen?

**Comment by JPT77** [comment]
Moin
Also Anwendungsfall wäre für mich vor allem, wenn es doppelte Buchungen gibt, die sich gegenseitig aufheben. 
Beispielsweise die Gegenbuchung gegenüber der Sammelbuchung zu den Mitgliedsbeiträgen.
Ist einfacher zu kontrollieren, wenn man beide gleichzeitig sieht.

Dafür würde ich keine zusätzliche externe Konfig machen, sondern direkt dort ein Häkchen  "Vorzeichen ignorieren"?

das mit den Nachkommastellen könnte man automatisch aktivieren, wenn glatte Beträge angegeben wurden. Dann von betrag-0.99 bis betrag+0.99?

**Comment by mbmueller** [comment]
Die Frage ist halt, wird dieses Feature so oft benötigt, dass sich hierfür ein eigener GUI-Punkt lohnt? Eventuell ließe sich da auch was mit einem Prefix in dem Betragsfeld arbeiten, sowie man jetzt ja zum Beispiel schon nach einer Range filtern kann.
Da man auch nach Ranges filtern kann, halte ich das Runden für Überflüssig und würde die Dinge nur unnötig obfuscaten.

**Comment by JPT77** [comment]
Äh. beziehst du dich mit dem letzten jetzt auf das Runden?
ja, wenn man bereits einen bereicht angeben kann, dann hat sich das wohl erledigt
