### ISSUE TITLE
MariaDB 11 Kompatibilität testen

### ISSUE THREAD

**Issue by lukas-mertens** [openjverein/jverein#203]
In meiner Installation die gerade noch auf MariaDB 10 und jverein/jverein (nicht openjverein/jverein) basiert, ist mir aufgefallen, dass ein Update meines Docker-Containers von MariaDB 10 auf latest verhindert, dass sich jverein mit der DB verbinden kann. Da ich derzeit nicht gut nachstellen kann, ob das ein persönliches Problem oder ein allgemeines Thema ist, hier einmal ein Issue. Es wäre schön, wenn einmal jemand testet, ob die neueste MariaDB als Datenbank nutzbar ist.

**Comment by willuhn** [comment]
OpenJVerein kann prinzipiell MariaDB.

**a)** Entweder in der Form, dass die MariaDB noch den Kompatibilitätsmodus mit MySQL hat (vermutlich bis incl. Version 10) und OpenJVerein gar nicht "merkt", dass es sich um MariaDB statt MySQL handelt.

**b)** Oder in der Form, dass MariaDB explizit konfiguriert ist. Hierzu sind 2 Dinge erforderlich:

1) Eine Jameica-Version, die den MariaDB-Treiber enthält. Ist im NIghtly-Build von Jameica ab ca. August 2023 der Fall. Im aktuellen Release noch nicht. Siehe https://www.willuhn.de/blog/index.php?/archives/885-Umstellung-von-MySQL-auf-MariaDB.html

2) In der OpenJVerein-Konfigurationsdatei "~/.jameica/cfg/de.jost_net.JVerein.rmi.JVereinDBService.properties" der MariaDB-Treiber eingestellt wurde:

```
database.driver.mysql.jdbcdriver=org.mariadb.jdbc.Driver
```
und die JDBC-URL so angepasst wurde, dass auch der MariaDB-Treiber verwendet wird ("jdbc\:mariadb" statt "jdbc\:mysql"):

```
database.driver.mysql.jdbcurl=jdbc\:mariadb\://<Server-IP>\:<port>/<datenbankname>?useUnicode\=Yes&characterEncoding\=ISO8859_1
```

**Comment by lukas-mertens** [comment]
@willuhn Danke, das erklärt es!
