### ISSUE TITLE
Fehler beim Speichern von Mitgliedern

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#208]
Hallo Jungs, ich habe ein Problem, kann es aber nicht selbst lösen.
Ich bekomme einen Fehler wenn ich Mitglieder speichern will deren ID im Bereich 1 .. 13 (evtl. 14 aber die kommt nicht vor bei mir) ist. Ich habe externe Mitgliedsnummer aktiv, sie entsprechen aber der original ID.
Es sind zwei Einträge in der Eigenschaften Tabelle.
![Screenshot_20240412_112608](https://github.com/openjverein/jverein/assets/126261667/bbc2538d-b9d4-4021-945c-280bccd850cb)

Es passiert an dieser Stelle beim while Zeile 3400 in MitgliedControl.java:
          DBIterator<Eigenschaften> it = Einstellungen.getDBService()
              .createList(Eigenschaften.class);
          it.addFilter("mitglied = ?", new Object[] { getMitglied().getID() });
          while (it.hasNext())
Es kommen dann folgende Meldungen wobei die Row Nummer unterschiedlich ist je nach ID:
[Fri Apr 12 10:21:14 CEST 2024][ERROR][main][de.jost_net.JVerein.gui.control.MitgliedControl.handleStore] Fehler bei Speichern des Mitgliedes
java.rmi.RemoteException: unable to init iterator. statement: prep8789: select EIGENSCHAFTEN.* from EIGENSCHAFTEN where mitglied = ? {1: '13'}; nested exception is: 
	org.h2.jdbc.JdbcSQLTimeoutException: Zeitüberschreitung beim Versuch die Tabelle {0} zu sperren
Timeout trying to lock table {0}; SQL statement:
select EIGENSCHAFTEN.* from EIGENSCHAFTEN where mitglied = ? [50200-199]

weiter unten:
Caused by: org.h2.jdbc.JdbcSQLTransientException: Row "72" not found in primary index "PUBLIC.EIGENSCHAFTEN_DATA" [90143-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:621)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)

**Comment by JohannMaierhofer** [comment]
Ich habe jetzt eine neue Datenbank aufgesetzt. Da kann ich ein Mitglied mit ID 1 erzeugen und speichern.
Evtl. ist da etwas mit meiner Datenbank nicht in Ordnung. 
Allerdings passiert es auch bei meinen beiden Produktiv Systemen. Beim einen nur bis ID 7.

**Comment by JohannMaierhofer** [comment]
Es waren korrupte Datenbanken. Ich habe jetzt mit Recover die Datenbanken korrigiert.
Meine Frage wäre aber trotzdem warum alle meine Datenbanken an dieser Stelle bzw. der Eigenschaften Tabelle korrupt waren. Kann es an einem Programierfehler liegen?

Gibt es noch andere Nutzer die Eigenschaften definiert haben und evtl. auch wieder welche gelöscht haben, die ein ähnliches Problem haben.
Der Test ist einfach, einfach ein Mitglied mit ID 1 öffnen und auf Speichern drücken.

Jedenfalls habe ich ein ungutes Gefühl wenn die Datenbank korrupt wird.

**Comment by JohannMaierhofer** [comment]
Man kann eine Eigenschaft nicht löschen wenn sie von einem Mitglied belegt ist, das wird im Code abgefangen.
Löscht man ein Mitglied, werden die referenzierten Eigenschaften des Mitglieds von der DB selbst gelöscht.
Außer Mitglied und Eigenschaft gibt es keine Verweise auf die Tabelle.
Das seltsame ist ja, dass das Speichern bei größeren Mitglieder IDs funktioniert.

Auch kann man die Eigenschaften der problematischen Mitglieder anzeigen. Da passiert allerdings folgendes Query:
it2.addFilter("mitglied = ? AND eigenschaft = ?",   new Object[] { mitglied.getID(), eigenschaft.getID() });
Also hier wird nach mitglied und eigenschaft gefiltert. Beim Speichern nur nach mitglied.

**Comment by JohannMaierhofer** [comment]
Jetzt bin ich einen Schritt weiter. 
Ich habe ein komplettes Backup inkl. der Plugins welches auf dem Stand vom alten JVerein 2.8.18 war. Damit konnte ich die Mitglieder z.B. mit ID 1 öffnen und speichern.
Ich habe dann JVerein 2.8.18 deinstalliert und das neue Open JVerein Repository eingetragen. Danach die Version 2.8.21 aus dem Repository installiert. Anschließend habe ich das Mitglied mit der ID 1 geöffnet und versucht zu speichern. Aber nun tritt genau der gleiche Fehler wieder auf.
Also muss das Problem bei der Migration von 2.8.18 auf 2.8.21 entstanden sein.
Es sind allerdings in der Datenbank keine Eigenschaften definiert. Die Eigenschaftentabelle muss also leer sein.

**Comment by JohannMaierhofer** [comment]
Jetzt habe ich wieder das alte Backup genommen und Open JVerein Version 2.8.20 manuell installiert.
Damit tritt das Problem noch nicht auf.
Anschließend habe ich 2.8.21 manuell installiert und jetzt ist der Fehler wieder da.  Also ist die Migration von 2.8.20 auf 2.8.21 da Problem.

**Comment by JohannMaierhofer** [comment]
Ich habe es weiter eingegrenzt. Es passiert bei "Feature gegenbuchung (#138)" mit Update0430.

**Comment by JohannMaierhofer** [comment]
Jetzt habe ich eine Entdeckung gemacht.
In meiner Konto Tabelle sind 13 Konten eingetragen. Genau bei den Mitgliedern mit den IDs 1..13 tritt das Problem beim Query der Eigenschaften Tabelle auf.
Bei meinem zweiten Verein habe ich 7 Konten, wie oben erwähnt hatte ich da das Problem bei den IDs 1..7.

**Comment by JohannMaierhofer** [comment]
Ich habe jetzt einmal eine neue Datenbank mit 2.8.20 erzeugt und Mitglieder und Konten eingegeben. Dann auf 2.8.21 migriert. Es tritt der Fehler nicht auf. Es ist also wohl kein generelles Problem.
Es wird also an meinen Datenbanken liegen. Sie wurden im Jahr 2018 erzeugt. Da ich sie korrigieren konnte hoffe ich mal, dass sich das Problem für mich gelöst hat.
Sollte noch jemand das gleiche Problem haben kann er mit den Befehlen unten die Datenbank korrigieren. Die Befehle sind für Linux. Man muss den Pfad zum jar file anpassen. Für Windows wohl mv durch move ersetzen und / durch \. Geht alles gut kann man den old Ordner löschen.

java -cp /opt/jameica/lib/h2/h2*.jar org.h2.tools.Recover
mkdir old
mv jverein.mv.db old
mv jverein.trace.db old
java -cp /opt/jameica/lib/h2/h2*.jar org.h2.tools.RunScript -url jdbc:h2:./jverein -user sa -script jverein.h2.sql
rm jverein.h2.sql

**Comment by EisW** [comment]
Ich hatte einen ähnlichen Fehler mit Version 2.8.21 von JVerein:
- Neuanlegen von Mitgliedern funktionierte
- in den neuen was ändern auch
- bestehende Mitglieder konnten nicht mehr verändert werden. Sollbuchung im Betrag ändern hat geklappt, aber namentlich eine Kündigung eintragen nicht (sinngemäß: Fehler im Primärschlüssel, habe keinen Screenshot gemacht, könnte ich bei Bedarf sicher aus einem Backup erzeugen)

Aber letztlich: **Danke** für das Posten der Recovery-Prozedur, die hat mir geholfen -> jetzt geht wieder alles, kein generelles Problem, auch hierwohl die Ursache die Migration ...

**Comment by JohannMaierhofer** [comment]
Ich habe jetzt etwas gefunden, bin mir aber nicht sicher ob das wirklich die Ursache sein kann.
In der Tabelle Konto habe ich die Spalte buchungsart hinzugefügt. Das wäre aber ein Foreign Key in die Buchungsart Tabelle. Diese Definition fehlt in Update0430.
Kann das die Ursache sein?
Und wie müsste die korrekte Migration lauten? Ich kenne nicht in dieser Beziehung nicht so aus.
Kann man dann die Datei Update0430 korrigieren für Leute die die Migration noch nicht gemacht haben. Und was muss man machen bei denen die die Migration schon gemacht haben?

**Comment by JohannMaierhofer** [comment]
Der Fehler ist nicht gelöst. Ich denke aber, dass das ein Fehler der Datenbank ist den wir nicht lösen können.
Ich sehe keinen Grund warum das Einfügen einer Tabellenspalte fehlerhaft sein sollte. Wir machen das ja auch sonst auf die gleiche Art und es gab nie ein Problem.

**Comment by lenilsas** [comment]
Dan können wir das Issue schließen?
