### ISSUE TITLE
Mitarbeit

### ISSUE THREAD

**Issue by kpatzwald** [openjverein/jverein#22]
Hallo,

ich würde auch gerne aktiv am Projekt mitarbeiten.

Viele Grüße
Kay

**Comment by phschoen** [comment]
Hab dir eine Einladung geschickt :)

**Comment by kpatzwald** [comment]
Danke, bin beigetreten. Gibt es schon eine Art Workflow? Arbeitet jeder weiterhin in seinem Fork?
