### ISSUE TITLE
Problem bei Projektzuordnung bei Splitbuchungen (Gegenbuchung)

### ISSUE THREAD

**Issue by lukas-mertens** [openjverein/jverein#231]
**Erwartetes Verhalten**
Ich öffne eine Buchung, weise ein Projekt hinzu und die Buchungsart Splitbuchung. Anschließend erzeuge ich eine Splitbuchung. Nun wird im Fenster der Splitbuchung eine Gegenbuchung mit gleichem Betrag angelegt, ebenfalls auf "Splitbuchung". Diese Gegenbuchung sollte automatisch dem gleichen Projekt zugeordnet sein, sonst gibt es später im Projektsaldo Fehler in der Berechnung. 

**Tatsächliches Verhalten**
Die Gegenbuchung ist keinem Projekt zugeordnet.

**Comment by JohannMaierhofer** [comment]
Ich habe das in #105 behoben.

**Comment by lukas-mertens** [comment]
@JohannMaierhofer Ah, perfekt, dann wurde das also direkt mitbehoben, dann freue ich mich schon auf den nächsten Release. Danke!
