### ISSUE TITLE
Langsame Darstellung der Buchungen bei Remote-Datenbanken

### ISSUE THREAD

**Issue by SchachtnerTh** [openjverein/jverein#268]
Hallo zusammen,

ich möchte nochmal auf ein Thema zurückkommen, das bereits in #159 angesprochen wurde.
Das Laden der Buchungen aus der Datenbank dauert sehr lange. Ich habe meine MariaDB-Datenbank über eine SSH-Verbindung angebunden und für diesen Anwendungsfall wäre es vermutlich am besten, wenn man alle Datensätze mit einer Abfrage abholen würde anstatt die über einen Iterator durchzulaufen und dann für jede Buchung eine Datenbankabfrage zu machen. (Zumindest hätte ich das mal ausprobieren wollen...)

Ich würde mir das auch gerne selber anschauen, verstehe aber nicht ganz, wie das funktioniert. `Buchung` scheint ja ein Interface zu sein, weshalb ich mich schwer tue, über einen ResultSetExtractor eine `List<Buchung>` zu erzeugen, ohne nicht eine Klasse zu erstellen, in der ich die -zig Methoden des Interfaces implementieren muss.
Kennt sich da vielleicht zufällig jemand damit aus? Laufe ich überhaupt in die richtige Richtung?
Irgendwelche Ideen, wie ich das angehen könnte?
Oder ist das zu aufwendig für einen schlechten Freizeitprogrammierer wie mich?

**Comment by lenilsas** [comment]
Ich habe in #269 einige Caches eingebaut, so sollte es deutlich schneller laden. Kannst du das bitte testen.

**Comment by SchachtnerTh** [comment]
Ich hab jetzt nicht die Zeit, das ausführlich zu testen, aber das sieht ja super aus!
Die Buchungen laden jetzt blitzschnell
Ich schau mir das später nochmal genauer an.
