### ISSUE TITLE
Weiteres vorgehen bei Änderungen

### ISSUE THREAD

**Issue by ghost** [openjverein/jverein#29]
Hallo,

nachdem es scheinbar ein paar Merges/Commits im jVerein Repository gab würde mich interessieren wie wir hier weiter machen?

Also ob die Commits einfach so übernommen werden. Bin mit github nicht so vertraut und weiß deshalb nicht ob das überhaupt möglich ist.

Oder soll hier für die Änderungen dann jeweils ein Pull request erstellt werden?

**Comment by wuschLOR** [comment]
Es wäre toll, wenn wir mehr Informationen bekommen könnten. 

Schade, dass seit Oktober hier nichts mehr passiert ist. 

Ich weiß aktuell nicht, auf welchen Fork ich setzen soll - den hier oder den von Heiner.

**Comment by MSchmalzl** [comment]
Es ist ja so, dass Heiner (der ursprüngliche Entwickler von jVerein) sich seit einigen Jahren einer Online-Vereinsverwaltung widmet und so keine Zeit mehr für jVerein bleibt.

Die Frage ist vor kurzem auch im jVerein-Forum aufgetaucht. Philipp (der Ersteller der openjVerein Organisation) ist Stand Anfang August im Urlaub.

Meiner Meinung nach ist der Gedanke mit der openJVerein Organisation zukunftsfähiger als wenn alles nur auf Schulter lastet.

Ich würde einfach mal noch ein paar Wochen warten. Dann haben wir hoffentlich eine Aussage dazu ob es mit der openJVerein Organisation weiter geht.

**Comment by willuhn** [comment]
> Gibt es irgendwo eine Zusammenschrift, wie es zu dem Fork gekommen ist?

Zu dem Fork kam es aufgrund dieses Threads im Forum unter https://jverein-forum.de/viewtopic.php?t=7123

> Vielleicht könnte es auch gut sein GitHub Discussions für die Organisation oder dieses Projekt zu aktivieren, sodass sich dort nichttechnische Themen besser diskutieren lassen.

Ich persönlich würde keinen zweiten Diskussionskanal öffnen. Das zumindest aus meiner Erfahrung mit Hibiscus. Am Ende laufen die Themen ja doch bei den selben Personen zusammen. Nur mit dem Unterschied, dass die dann teilweise die selben Themen auf unterschiedlichen Plattformen diskutieren. Das existierende JVerein-Forum finde ich selbst ausreichend zum Diskutieren. Aber wie gesagt - das ist meine persönliche Erfahrung.

> Ich pers. finde es toll, dass @willuhn offiziell dabei ist, was mir in seiner Rolle als langjähriger, vertrauenswürdiger Maintainer der Jameica/Hibiscus Platform nahelegt, dass diese langfristig unterstützt wird.

Danke. Auch wenn ich selbst JVerein nutze, ist zumindest meine Wahrnehmung, dass es von vielen Vereinen genutzt wird und daher auch für die Gesellschaft eine gewisse Bedeutung hat.

**Comment by MSchmalzl** [comment]
Derzeit reichen wir die Änderungen als jeweils separaten PR ein um diese nochmals zu prüfen.
