### ISSUE TITLE
Fehler bei Kontoauszug

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#30]
Es gibt einige Fehler beim Erzeugen eines Kontoauszugs:
1. Beim Starten des Dialogs "Kontoauszug" aus dem Mitgliedskonto wird im Kontoauszug Dialog eine Zeitraum Gruppe und ein Button "starten" erzeugt (KontoauszugView.java). Dabei wird sofort das aktuelle Start und Ende Datum an den Button übergeben. Ändert man den Zeitraum im Dialog und ruft dann "starten" auf wird der geänderte Zeitraum ignoriert. Man muss also erst den Zeitraum ändern, aus dem Dialog rausgehen und erneut reingehen damit der geänderte Zeitraum benutzt wird.
2. Ein Ändern des Zeitraums über die Eingabefelder im Kontoauszug Dialog ist nicht persistent. Damit funktioniert obiges Verfahren nicht da mit Verlassen des Dialogs die geänderten Werte weg sind und beim Öffnen wieder die alten Werte erscheinen. Ein persistentes Ändern lässt sich nur über den Kalender Button "..." erreichen. Hier bleiben die geänderten Werte nach Verlassen des Dialogs erhalten.

**Comment by mta4racer** [comment]
Mit dem 1. Problem hat sich Dennis Schlevoigt schon beschäftigt:

https://github.com/schlevoigt/jverein/commit/2d05760ef56836f1f661ba527ba7690f7e1ca70f#diff-3d672c272c8ba7dc0d28294c194b3ae71974af4acca2e168946577bd4d4008f0

Bzgl. der nicht persistenten Datumswerte. Hier fehlt eine SaveSettings Funktion.

**Comment by MSchmalzl** [comment]
Mit dem 1. Problem hat sich Dennis Schlevoigt schon beschäftigt:
https://github.com/schlevoigt/jverein/commit/2d05760ef56836f1f661ba527ba7690f7e1ca70f#diff-3d672c272c8ba7dc0d28294c194b3ae71974af4acca2e168946577bd4d4008f0

Zum 2. Problem. Hier fehlt eine SaveSettings-Funktion.
