### ISSUE TITLE
Fehler beim Verwendungszweck einer Sammellastschrift BUG

### ISSUE THREAD

**Issue by siegfried62** [openjverein/jverein#308]
Hallo,
Wenn ich bei einem Mitglied Sekundäre Beiträge einziehe, dann steht in der Sammellastschrift bei dem Mitglied im Verwendungszweck z.B."ZWEIER, EINER 20.00, ERWA 108.00, Wohnwagen 180.00"
Bei der ersten Angabe fehlt immer der Betrag. Hier ZWEIER 20.00
Bei anderen Mitgliedern steht z.B. Einer an erster Stelle und dann ist hier auch **kein** Betrag vorhanden.
Egal welcher Sekundäre Beiträge an erster Stelle steht, ist dort kein Betrag vorhanden.

Da viele Mitgliedern deshalb irritiert sind und immer wieder nachfragen kommen, möchte ich fragen ob dieser Fehler behoben werden kann.  Siegfried

**Comment by lenilsas** [comment]
Der Fehler ist in der neuen Obantoo Version behoben, diese ist im Hibiscus Nigthly Build enthalten.

**Comment by siegfried62** [comment]
Danke
