### ISSUE TITLE
Mail-Sortierung nach Nr. nicht numerisch

### ISSUE THREAD

**Issue by mbmueller** [openjverein/jverein#320]
Die Sortierung der Mails nach Nr. ist lexikographisch und nicht numerisch.
Also bspw. `99 > 969`
![image](https://github.com/user-attachments/assets/37350848-a124-42b2-b4cc-809d4e7b21cf)

**Comment by JohannMaierhofer** [comment]
Das Problem gibt es auch für die Ids in den Views für Spendenbescheinigungen, Lastschriften und Jahresabschlüsse.
Das sollte man so lösen wie bei Mitglied Id implementiert.

**Comment by lenilsas** [comment]
Das kann man auch lösen, indem man in der MailImpl etc. Bei getAttribute folgendes einfügt:
```
if ("id-int".equals(fieldName))
    {
      try
      {
        return Integer.valueOf(getID());
      }
      catch (Exception e)
      {
        Logger.error("unable to parse id: " + getID());
        return getID();
      }
    }
```
Anschließend kann man im Control die Spalte per "id-int" statt "id" hinzufügen.
Dass müsste man in allen Implantations machen bei denen die Id als Spalte angezeigt wird.

**Comment by lenilsas** [comment]
Habe ich in #322 umgesetzt. Allerdings nicht bei Externe Mitgliedsnummer da diese nicht unbedingt nur nummerisch sein muss.
