### ISSUE TITLE
Button Variablen anzeigen in Mail-Vorlage

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#360]
Es wäre sehr praktisch, wenn man bei der Erstellung von Mail-Vorlagen auch den Button "Variablen anzeigen" zur Verfügung hätte, wie er im Skript-Editor von Lesefeldern angezeigt wird.

**Comment by lenilsas** [comment]
Bei Mails gibt es diesen Dialog. Ich mache es immer so, dass ich erst mal eine Mail schicke, und dann, wenn ich sie mehrfach brauche, den Inhalt in eine Vorlage kopiere.

**Comment by tolot27** [comment]
> Bei Mails gibt es diesen Dialog. Ich mache es immer so, dass ich erst mal eine Mail schicke, und dann, wenn ich sie mehrfach brauche, den Inhalt in eine Vorlage kopiere.

Ja, ich weiß. Zwar etwas versteckt über Rechtsklick auf den Empfänger. Aber zu finden sind sie. Da ich gleich mit Vorlagen gestartet habe, habe ich den Button vermisst.

Der Issue kann ja als "good first issue" getaggt werden und ich nutze es als ersten PR. 😏

**Comment by mbmueller** [comment]
@tolot27 möchtest du da noch dran arbeiten?
