### ISSUE TITLE
Rechnung erstellen von Versand trennen

### ISSUE THREAD

**Issue by lenilsas** [openjverein/jverein#365]
Bei der aktuellen Implementierung der Rechnung stört mich, dass die Rechnungen direkt beim Versand erstellt werden. Es wird jedoch nirgends die Rechnung gespeichert und welche Buchungen zu ihr gehören. So kann man über Beiträge mehrfach Rechnungen schreiben. Auch werden bei jedem Versenden oder Drucken die Rechnungsnummern hochgezählt. Wenn man also die Rechnungen einmal als PDF erstellt um sie zu prüfen und dann die Mails versendet haben sie unterschiedliche nummern.
Mein Vorschlag wäre es ähnlich wie bei den Spendenbescheinigungen umzusetzen. Dass in einer View die Rechnungen erstellt werden, in einer neuen DB Tabelle gespeichert werden und bei den zugehörigen Sollbuchungen die RechnungID eingetragen wird. Der Versand erfolgt unabhängig davon in der jetzigen View.
Auch bei den Mahnungen würde ich es so verändern, dass sich diese auf die Rechnungen beziehen.
Was haltet ihr von dem Änderungsvorschlag?

**Comment by JohannMaierhofer** [comment]
Ich finde den Vorschlag gut. Ich selbst erzeuge keine Rechnungen und Mahnungen. Darum ist es für mich nicht so wichtig. Wenn ich aber welche erzeugen würde, würde ich mir es nach deinem Vorschlag wünschen.

Bevor du anfängst, würde ich dich bitten meinen PR #307 zu reviewen. Der hat viele Dateien geändert und es kommt immer wieder zu Merge Konflikten. Es wäre schön wenn der übernommen wäre.

**Comment by lenilsas** [comment]
Ich habe mit dem Review schon angefangen, da es viele Dateien sin dauert es etwas.
Bis ich mich an die Umsetzung der Rechnungen mach wird es wahrscheinlich auch noch etwas dauern.
