### ISSUE TITLE
Anzahl nötiger Reviewer auf 1 reduzieren

### ISSUE THREAD

**Issue by willuhn** [openjverein/jverein#37]
Derzeit ist das Projekt so konfiguriert, dass zwei Reviewer nötig sind, um einen Pull-Request (PR) in den Master-Branch zu übernehmen. Da der Einreicher des PR nicht gleichzeitig seine eigene Änderung reviewen darf, sind in Summe 3 Personen für eine Code-Änderung erforderlich. Einer, der die Änderung in seinem Fork schreibt und als PR einreicht - und dann nochmal 2 User, die beide ihr OK für die Übernahme der Änderung geben. Ich würde vermuten, dass PRs perspektivisch deshalb liegen bleiben, weil sich kein zweiter Reviewer findet. Damit etwas Schwung in die Entwicklung kommt, würde ich vorschlagen, die Anzahl der Reviewer erstmal auf 1 zu reduzieren. Wenn man annimmt, dass bereits der Autor des PR sorgsam gearbeitet hat, ist ja zusammen mit dem Reviewer ein 4-Augen-Prinzip gewährleistet, was aus meiner Sicht hinreichend sicher ist.

Wenn die Entwicklung in Zukunft etwas Fahrt aufgenommen hat und mehr aktive Mitglieder existieren, kann man das irgendwann sicher auch wieder auf 2 setzen.

**Comment by phschoen** [comment]
Ich bis jetzt bin ich der Auffassung, dass dadurch "schnellere" Fehler verhindert werden, vor allem so lange wir keine Unit-Tests haben etc. würde ich es gerne auf 2 lassen. Auch um mehr Leute zum Einbeziehen in der PR zu bekommen, finde ich die 2 angemessen. 

Wenn wir Unittests haben, welche auch pro PR gebaut werden, können wir ja nochmal darüber reden.

**Comment by willuhn** [comment]
OK. Bei den letzten PRs haben sich ja immer 2 Reviewer gefunden. Dann lassen wir es erstmal so. In der Hoffnung, dass das derzeitige Momentum hier erhalten bleibt.
