### ISSUE TITLE
Buchungszuordnung sollte nur von Zahlungsart der Buchung abhängen

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#386]
Wenn man Sollbuchungen hat, wo als Zahlungsweg Überweisung gewählt ist, funktioniert die Buchungszuordnung der eingegangenen Überweisung anhand der IBAN nicht, wenn beim Mitglied der Zahlungsweg != Überweisung ist. Sobald ich den Zahlungsweg des Mitglieds auf Überweisung ändere, funktioniert die Zuordnung.

Meiner Ansicht nach sollte das völlig unabhängig von dem Zahlungsweg des Mitglieds sein, sondern ausschließlich von der Sollbuchung abhängen.

**Comment by lenilsas** [comment]
in #394 umgesetzt
