### ISSUE TITLE
Ant durch Maven oder Gradle ersetzen

### ISSUE THREAD

**Issue by almereyda** [openjverein/jverein#40]
@tobidope hat in #9 vorgeschlagen Ant durch Maven oder Gradle zu ersetzen, da diese ein moderneres Build Tooling for Java bieten.

**Comment by BT-11** [comment]
ich würde für maven stimmen. könnte das umsetzen.

**Comment by almereyda** [comment]
Würde mich bereit erklären dass danach nach

- #39

zu hieven. Das wäre auch eine gute Validierungsmöglichkeit zur Gegenprüfung.

**Comment by willuhn** [comment]
@BT-11 Wenn du es umsetzen kannst, dann könntest du doch einfach einen Pull Request damit einreichen.

**Comment by BT-11** [comment]
Ich sehe gerade, dass in Jameica und auch in Hibiscus schon Gradle verwendet wird. Macht es da Sinn hier in JVerein auf Maven zu gehen?

**Comment by willuhn** [comment]
Ich verwende nur die "download.gradle" Scripts zum Herunterladen der Abhängigkeiten. Zum Bauen nutze ich leider nach wie vor auch Ant, da nur dort das Signieren der JARs und Artfakte funktioniert. Hinzu kommt, dass in den Gradle-Scripts (die stammen nicht von mir sondern wurden als Pull-Request erstellt) user-spezifische Plugins verwendet wurden).

**Comment by mbmueller** [comment]
Passiert hier noch etwas? Ansonsten würde sich anbieten das Issue zu schließen.

**Comment by tolot27** [comment]
> Ich verwende nur die "download.gradle" Scripts zum Herunterladen der Abhängigkeiten. Zum Bauen nutze ich leider nach wie vor auch Ant, da nur dort das Signieren der JARs und Artfakte funktioniert. Hinzu kommt, dass in den Gradle-Scripts (die stammen nicht von mir sondern wurden als Pull-Request erstellt) user-spezifische Plugins verwendet wurden).

Hmm, wo finde ich die diese scripts? Hier im repo vermisse ich sie.

Ich bin schon für einen dependency manager. Dann könnten wir jars wieder aus dem repo entfernen.

**Comment by willuhn** [comment]
> Hmm, wo finde ich die diese scripts? Hier im repo vermisse ich sie.

Das bezog sich auf Jameica/Hibiscus.
