### ISSUE TITLE
Bei Nicht-Mitglieder sollte kein Vollzahler angeboten werden 

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#403]
Bei Nicht-Mitglieder kann man den Zahlungsweg Vollzahler auswählen. Das sollte nicht sein.

**Comment by mbmueller** [comment]
Bearbeitest du den Issue? Falls nein, würde ich den übernehmen, bräuchte dann aber kurz noch 1-2 Screenshots was du meinst.

**Comment by mbmueller** [comment]
Aber müsste dann nicht der ganze Bereich Zahlung raus?

**Comment by lenilsas** [comment]
Ich kümmere mich darum
