### ISSUE TITLE
Zusatzbetrag mit anderem Zahlungsweg

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#420]
Wir haben immer mal wieder Zusatzbeträge, die die Mitglieder lieber überweisen wollen, statt das sie per Lastschrift eingezogen werden (z. B. weil die Beträge recht hoch sind oder das Datum flexibler gewählt werden soll). Daher wäre es ganz gut, wenn man bereits bei der Erstellung des Zusatzbetrags angegeben könnte, wie der Zahlungsweg ist (vorbelegt mit Zahlungsweg aus Mitgliedsstammdaten). Dies sollte dann auch mit in der Vorlage gespeichert werden können.
Beim Abrechnungslauf muss entsprechend berücksichtigt werden, dass dann nur für Lastschriften eine Abbuchungsausgabe erzeugt wird. Die beim Abrechnungslauf erzeugten Sollbuchungen werden ja bereits mit einem Zahlungsweg versehen. Dieser müsste dann dem Zusatzbetrag entnommen werden und nicht aus den Mitgliedsstammdaten.

**Comment by lenilsas** [comment]
Das werde ich demnächst machen, auch #421.
