### ISSUE TITLE
Abrechnungslauf: PDF-Ausdruck ist unsortiert

### ISSUE THREAD

**Issue by JPT77** [openjverein/jverein#432]
Hallo, 

ich lasse den Abrechnungslauf immer eine PDF datei erstellen um mit deren Hilfe nochmal über alle Mitglieder zu gehen und zu prüfen ob alles stimmt (blöderweise setzte JVerein beispielsweise nicht den Zeitraum, für den abgebucht wird. das mache ich manuell)
Ich glaube, das Feld ist *SEPA-Datei drucken*. Egal. Jedenfalls scheint der Inhalt der PDF Datei unsortiert. Ich würde mir wünschen, dass er nach einem Feld der Mitgliederliste sortiert wäre. Ob das jetzt Mitgliedsnummer, Nachname oder was anderes ist, wäre mir erst mal egal. 

Workaround ist, einen Screenshot der eingestellen Sammellastschrift zu machen. Die kann ich nämlich sortieren.

Dankeschön

Version 2.8.22

**Comment by lenilsas** [comment]
> (blöderweise setzte JVerein beispielsweise nicht den Zeitraum, für den abgebucht wird. das mache ich manuell)

Was meinst du damit, welcher Zeitraum wird wo nicht gesetzt?

**Comment by JPT77** [comment]
> Was meinst du damit, welcher Zeitraum wird wo nicht gesetzt?

Ich setze den Verwendungszweck auf zb "Mitgliedsbeitrag 24/11". Für Mitglieder, die monatlich zahlen passt das, für die anderen passe ich es manuell an, wenn ich es merke. wenn nicht, dann auch egal ;)

Von JVerein wird dann Mitgliedsnummer und Name vorangestellt.

**Comment by lenilsas** [comment]
Momentan ist die Liste nach MitgliedsID sortiert (nicht aber nach der ExternenId falls vorhanden)

**Comment by lenilsas** [comment]
Im Verwendungszweck können auch Variablen verwendet werden. Über Lesefelder könntest du hier einen vom Zahlungstermin abhängigen Verwendungszweck realisieren.

**Comment by JPT77** [comment]
> Momentan ist die Liste nach MitgliedsID sortiert (nicht aber nach der ExternenId falls vorhanden)

ah. das hätte ich auch selbst merken können *patsch* 
Damit hat sich dieses Ticket eigentlich erledigt.

> Im Verwendungszweck können auch Variablen verwendet werden. Über Lesefelder könntest du hier einen vom Zahlungstermin abhängigen Verwendungszweck realisieren.

Das ist leider nicht besonders gut dokumentiert, aber ich habe gefunden:
https://openjverein.gitbook.io/doku/allgemeine-funktionen/abrech/abrechnung (dort steht nichts)
https://openjverein.gitbook.io/doku/sonstiges/variable

und Variablen werden verwendet mittels ${variable}

Das Eingabefeld ist viel zu klein um die viel zu langen Variablennamen sinnvoll nutzen zu können. 

es klappt. Ja, das ist jetzt garnicht so schlecht. Ergebnis ist: 

    ${aktuellermonat} ${mitglied_zahlungstermin}

zwei Probleme bleiben: 
- Aktueller Monat ist MM.JJ und damit leider nicht alphabetisch in chronologischer Reihenfolge zu sortieren
- Es ist fast kein Platz mehr im Eingabefeld. 

sollen wir ein ticket für das Thema aufmachen?

**Comment by lenilsas** [comment]
> Aktueller Monat ist MM.JJ und damit leider nicht alphabetisch in chronologischer Reihenfolge zu sortieren

Wo möchtest du es sortieren, welche View?

> Es ist fast kein Platz mehr im Eingabefeld.

Bei mir ist das Eingabefeld unter Abrechnung über die ganze breit und Meiner Meinung nach groß genug. Oder meinst du woanders?

Ja, die Dokumentation müssen wir noch verbessern, @JohannMaierhofer  ist gerade dabei sie zu überarbeiten

**Comment by JPT77** [comment]
> > Aktueller Monat ist MM.JJ und damit leider nicht alphabetisch in chronologischer Reihenfolge zu sortieren
> 
> Wo möchtest du es sortieren, welche View?

ufff. Ich erinnere mich nicht. Generell in den Kontoumsätzen? Das hat sich natürlich mit der Sammelbuchung erledigt. 
Im Mitgliedskonto? In den Buchungen?
ich bin jedenfalls nach anfänglicher anderer Formatierung zu diesem Format übergegangen eben wegen der besseren Sortierbarkeit.
Ich hatte am Anfang halt das reine Chaos, weil ein 3/4 Jahr keine Beiträge abgebucht worden waren. 

> > Es ist fast kein Platz mehr im Eingabefeld.
> 
> Bei mir ist das Eingabefeld unter Abrechnung über die ganze breit und Meiner Meinung nach groß genug. Oder meinst du woanders?

Das Feld ist über die ganze Breite. Aber es ist auf 50 Zeichen limitiert. Vermutlich von der Datenbank?

> Ja, die Dokumentation müssen wir noch verbessern, @JohannMaierhofer ist gerade dabei sie zu überarbeiten

ja, er ist schwer engagiert :)

**Comment by lenilsas** [comment]
> Das Feld ist über die ganze Breite. Aber es ist auf 50 Zeichen limitiert. Vermutlich von der Datenbank?

habe ich in #453 geändert

**Comment by JPT77** [comment]
> Momentan ist die Liste nach MitgliedsID sortiert (nicht aber nach der ExternenId falls vorhanden)

![image](https://github.com/user-attachments/assets/2cfb1f87-2c45-40a8-ad61-db8ceb13640a)

Nein, ist die nicht. Die Mitgliedsnummern sind wild durcheinander. 
Es ist mir immernoch komplett unklar, nach was das PDF sortiert ist.

**Comment by lenilsas** [comment]
Oh sorry ich dachte du meintest die Abrechnungslauf Ausgabe. Die PDF bei Abrechnung ist folgendermaen sortiert:

- Beiträge und Sekundäre Beiträge: `ORDER BY zahlungsweg, name, vorname` (das Sortieren nach Zahlungsweg ist wichtig, damit bei Familienangehörigen erst der Vollzahler und dann die Angehörigen abgerechnet werden.)
- Dann die Zusatzbeträge in der Reihenfolge der Eingabe
- Dann die Kursteilnehmer in der Reihenfolge der Eingabe

**Comment by JPT77** [comment]
Danach ist es aber ebenfalls nicht sortiert.
Bei mir ist nur punkt 1 relevant. 
das PDF enthalät per se nur Zahlungsweg=ABBUCHUNG, weil alle anderen ja nicht im PDF erscheinen.
Und was übrigbleibt ist nicht nach NAME sortiert. 

Ich glaube, wir reden immernoch aneinander vorbei ;)

das PDF welches durch "SEPA-Datei drucken" erzeugt wird, glaube ich

**Comment by lenilsas** [comment]
Bei kompakter Abbuchung sind die Zahlungen in einer unsortierten HashMap, ohne komprimiert so wie ich geschrieben habe.
Um das zu ändern müsste man die Lib Obantoo ändern, ich erstelle da mal einen PR
