### ISSUE TITLE
Fix merge conflict in /.gitignore file and remove /.cvsignore

### ISSUE THREAD

**Issue by BT-11** [openjverein/jverein#44]
solve konflikt in gitignore.
remove obsolete cvsignore file as we are on git now.

**Comment by BT-11** [comment]
Please assign this issue to me. I'll remove the .cvsignore and fix the merge-conflict artifacts out of .gitignore. This is a nobrainer task just for sanity. Only the organization owner is alble to assign issues to users.

**Comment by MSchmalzl** [comment]
Ich glaube es ist am einfachsten, wenn dazu einfach ein PR eingereicht wird.
