### ISSUE TITLE
BIC bei SEPA-Überweisung automatisch befüllen

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#447]
Ich weiß, für den deutschen SEPA-Zahlungsverkehr braucht man keine BIC mehr. In der Mitgliederverwaltung wird sie jedoch bei der Bankverbindung noch automatisch ausgefüllt. Das könnte so auch bei der SEPA-Überweisung sein. D. h. sobald man eine IBAN einfügt, könnte er die BIC automatisch ausfüllen.
Alternativ kann man das BIC-Feld ausblenden, sofern die IBAN von dem ausgehenden Konto das gleiche Länderpräfix wir die IBAN des Empfängers hat.

Issue triage: low priority

**Comment by tolot27** [comment]
Ah, ich glaub diesen Issue müsste ich bei Hibiscus erstellen, nur leider sind da Issues gesperrt.

**Comment by lenilsas** [comment]
Ja, das gehört nach Hibiscus.
Bis vor kurzem war es da auch so dass die BIC automatisch ausgefüllt wurde, da sie jedoch nicht mehr gebraucht wird, wird sie auch nichtmehr ausgefüllt. Du kannst das aber unter Hibiscus->Einstellungen->Grundeinstellungen aktivieren wenn du es noch brauchst

**Comment by tolot27** [comment]
Super, danke für die Info.
