### ISSUE TITLE
E-Rechnungen

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#454]
Für Vereine mit wirtschaftlichen Geschäftsbetrieb werden E-Rechnungen (ZUGFeRD) zur Pflicht.

Ab 2025 müssen diese Vereine E-Rechnungen empfangen können. Da Hibiscus diese importieren kann sollte das wohl erfüllt sein.

Für das Erstellen von E-Rechnungen gibt es Übergangsfristen bis Ende 2026/2027 falls der Empfänger zustimmt dass er die Rechnung per Papier oder Standard PDF erhält.

Es wäre also sinnvoll so ein Feature zu implementieren.

**Comment by lenilsas** [comment]
Ich kümmer mich darum
