### ISSUE TITLE
Zusätzliche Zahlungserinnerung zu Rechnung und Mahnung

### ISSUE THREAD

**Issue by mbmueller** [openjverein/jverein#459]
> Das Zuordnen eine Istbuchung ändert ja nichts an der Rechnung und am Rechnungsbetrag. Der Fehlbetrag kann sich ja ändern. Der ist ja dann für die Mahnungen relevant. Die Mahnung basiert halt auf dem Stand zum Tag der Erstellung. Ist ein Teilbetrag bezahlt wird die nächste Mahnung dann anders.

Ich verstehe jetzt was ihr meint. Mein Workflow ist da einfach anders als es durch die Änderung hier noch möglich sein wird.
Wir haben bei uns oft Mitglieder die nur einen Teil bezahlen und ich möchte sie ja vor allem daran erinnern, was sie noch zu bezahlen haben.
Ich habe deswegen folgendes Formular:
![image](https://github.com/user-attachments/assets/f00c538c-a737-4a23-a846-3665e1646f35)

Dadurch ergibt sich vor dem Zuordnen einer Istbuchung folgende Ausgabe:
[RECHNUNG-20241114-205334.pdf](https://github.com/user-attachments/files/17757067/RECHNUNG-20241114-205334.pdf)

Und nach Zuordnung bspw.:
[RECHNUNG-20241114-205435.pdf](https://github.com/user-attachments/files/17757068/RECHNUNG-20241114-205435.pdf)

In dem man statt "mitgliedskonto_differenz" einfach "mitgliedskonto_betrag" verwendet bleibt das natürlich gleich. Durch die Änderung fällt für mich aber die Möglichkeit einer "Zahlungserinnerung" weg, in der nur die Differenz angezeigt wird. 
Wäre aber auch etwas, was man in einem anderen Issue behandeln könnte, falls das überhaupt als sinnvoll erachtet wird.

_Originally posted by @mbmueller in https://github.com/openjverein/jverein/issues/418#issuecomment-2477313920_

**Comment by lenilsas** [comment]
Ist das nicht eine Mahnung? Ob man im Text "Zahlungserinnerung"  oder "Mahnung" schreibt kann man ja frei entscheiden, ansonsten sehe ich da keine Unterschiede.
