### ISSUE TITLE
Mitmachen

### ISSUE THREAD

**Issue by NicoB77** [openjverein/jverein#46]
Bitte in Organisation aufnehmen.

**Comment by MSchmalzl** [comment]
Sehe ich das richtig, dass du noch nicht in der OpenJVerein-Organisation dabei bist?

**Comment by phschoen** [comment]
@NicoB77 ich habe dir nochmals eine Einladung geschickt. Bitte innerhalb 7 Tage annehmen sonst müsste ich eine neue schicken. LG Philipp
