### ISSUE TITLE
Teilnehmen

### ISSUE THREAD

**Issue by FullHD23** [openjverein/jverein#47]
Hallo zusammen,
ich würde gerne teilnehmen und schauen ob ich helfen kann.

**Comment by MSchmalzl** [comment]
Auch hier die Frage: Kann es sein, dass du noch nicht Mitglied der OpenJVerein Organisation bist?

**Comment by FullHD23** [comment]
Das ist richtig. 
Ich bin zwar kein Informatiker, aber möchte gerne das Thema der Belegnummern integrieren.

**Comment by MSchmalzl** [comment]
Hast du eine Einladung erhalten?

**Comment by MSchmalzl** [comment]
Okay. @phschoen kannst du bitte nochmal eine Einladung an @FullHD23 rausschicken?

**Comment by phschoen** [comment]
@FullHD23 ich habe dir nochmals eine Einladung geschickt schau mal villeicht ist sie bei dir auch im Spam. Innerhalb von 7 Tagen musst du bestätigen ansonsten müsste ich nochmal eine Einladung schicken.
Wenn du drin bist gerne das Ticket schließen.

**Comment by FullHD23** [comment]
Hat nun geklappt, vielen Dank :-)
