### ISSUE TITLE
Lizensprobleme bei Verwendung von IText

### ISSUE THREAD

**Issue by lenilsas** [openjverein/jverein#471]
Momentan wird in JVerein (und auch in Hibiscus und Obantoo) iText für die Generierung der PDFs verwendet. Das ist aber Lizenzrechtlich nicht zulässig, da iText unter AGPLv3 veröffentlicht ist. Das bedeutet, dass es nur in Projekten verwendet werden darf die ebenfalls unter AGPLv3 lizenziert sind. Ansonsten ist eine kostenpflichtige Version nötig.
Alternativen sind: pdfbox, OpenPDF (oder eine ältere Version von iText 4.2.0, das ist jedoch nicht wirklich eine Lösung)

**Comment by JohannMaierhofer** [comment]
Pdfbox scheint nach Aussagen im Internet komplexer aber besser gepflegt. 

Umsteigen müssen wir wohl. 

Da könnte man gleich mit der Spendenbescheinigung starten und bei der Standard Spendenbescheinigung auf die vom Finanzamt aufsetzen und dort die Formulare füllen.

@tolot27 hat in #345 angeboten so etwas bis Ende das Jahres zu machen. Das wäre gut.

Ich würde gerne die Spendenbescheinigungen für 2024 per Mail verschicken. Wenn wir es nicht schaffen würde ich das noch in den alten Code einbauen.

**Comment by lenilsas** [comment]
Ich denke auch, dass PdfBox die bessere Variante ist. Ich kann beim Formularauswerter anfangen, da ich da mit den XRechnungen sowieso am verändern bin.

von @tolot27 habe ich das so verstanden, dass er ein XPDF, also ein ausfüllbares Formular mit Formularfeldern hat. Das hat nichts mit PdfBox zu tun. Und ich denke auch nicht, dass wir das brauchen, wir können ja wie bisher den Text einfach auf das Dokument schreiben.

**Comment by JohannMaierhofer** [comment]
Ja, die Forderung für gerduckte Unterschriften ist auch nur, dass die Bescheinigungen den offiziellen Formularen entsprechen müssen. So wie ich sie als letztes umgebaut habe ist das der Fall.

**Comment by JPT77** [comment]
> Momentan wird in JVerein (und auch in Hibiscus und Obantoo) iText für die Generierung der PDFs verwendet. Das ist aber Lizenzrechtlich nicht zulässig, da iText unter AGPLv3 veröffentlicht ist. Das bedeutet, dass es nur in Projekten verwendet werden darf die ebenfalls unter AGPLv3 lizenziert sind. Ansonsten ist eine kostenpflichtige Version nötig. Alternativen sind: pdfbox, OpenPDF (oder eine ältere Version von iText 4.2.0, das ist jedoch nicht wirklich eine Lösung)

Ich habe nach Unterschieden zwischen AGPLv3 und GPLv3 gesucht, und finde eigentlich nur, dass mit der AGPL ein Loch geflickt werden sollte, dass die OpenSource-Verpflichtung praktisch nicht aktiv war, wenn es sich um eine Webanwendung handelte (also kein binary ausgeliefert wurde).
Da es sich bei JVerein/Jameica nicht um eine Webanwendung handelt, ist das doch irrelevant?
Hast du eine Quelle, warum das inkompatibel sein soll?

**Comment by lenilsas** [comment]
Oh Entschuldigung, da habe ich den Text wohl falsch interpretiert, danke für deine Nachfrage. Ich habe immer mal wieder was über die Strenge Lizenz von iText gelesen und dann auf der Hompage von iText https://itextpdf.com/how-buy/AGPLv3-license gelesen und anscheinend die Restrictionen falsch verstanden.
Also kann alles beim alten bleiben!

**Comment by JPT77** [comment]
Mh, unter deinem Link steht aber tatsächlich

> It’s a legal violation to use iText Core/Community and our open source add-ons in a non-AGPL environment.

**Comment by lenilsas** [comment]
Ich habe [hier](https://itextpdf.com/blog/technical-notes/how-do-i-make-sure-my-software-complies-agpl-how-can-i-use-itext-free) ausfürlich informationen gefunden. Da steht nur das der Quelltet öffentlich sein muss, dass das ganze Project unter AGPL lizenziert sein muss steht dort nicht. Von dem her denke ich können wir es getrost dabei belassen.
