### ISSUE TITLE
Neues Release 2.8.20

### ISSUE THREAD

**Issue by willuhn** [openjverein/jverein#49]
Das letzte Release 2.8.19 stammt von Mai 2022. Inzwischen sind ja wichtige Bugs gefixt worden. Daher sollte wirklich mal ein neues Release 2.8.20 erstellt werden, welches zumindest diese Bugfixes für die Öffentlichkeit zugänglich macht.

Mit der Anleitung https://github.com/openjverein/jverein/blob/master/RELEASE.md konnte ich lokal ein neues Release 2.8.20 erzeugen.

Für die Schritte ab "Erstelle ein GIT-Tag ..." fehlen mir die Rechte hier im Projekt. Ich nehme an, das kann nur @phschoen ausführen?
Kannst du das bitte übernehmen?

Ich weiss, das ist derzeit noch ein manueller Prozess. Aber wenn wir erst den kompletten Prozess mit Github Actions & Co automatisieren, dann wird es hier nie ein neues Release geben.

**Comment by willuhn** [comment]
[jverein.2.8.20.zip](https://github.com/openjverein/jverein/files/12847746/jverein.2.8.20.zip)

**Comment by NicoB77** [comment]
Bevor ein neues Release veröffentlicht wird, sollten unbedingt die Probleme mit dem Abrechnungslauf behoben werden. Aktuell funktioniert nur die Ausgabe in eine Datei, nicht nach Hibiscus, wenn ein PDF der Sammellastschrift bestellt wurde, gibt es eine Exception, und das Feature "kompakte Abbuchung" funktioniert gar nicht.

**Comment by NicoB77** [comment]
Habe ich in #42 gemacht. Allerdings zusammen mit der Änderung, alle Lastschriften als Folgelastschrift einzureichen (das ist auch ein PR bei JVerein - von 2019). Die Änderung bei den Lastschriften hatte ich schon lange, und sie stehen an den gleichen Stellen im Code wie die Bugfixes. Beides zu trennen wäre mehr Aufwand gewesen.

**Comment by MSchmalzl** [comment]
Ich bin dafür.

**Comment by willuhn** [comment]
@phschoen Wir brauchen deine Hilfe. Wie wollen wir vorgehen? Kann ich dir helfen? Bauen kann ich das Release - zum Veröffentlichen fehlen mir aber die Rechte. Kannst du das übernehmen?

**Comment by MSchmalzl** [comment]
Ich finde es nicht gut, dass nur eine Person volle Berechtigungen auf die OpenJVerein Organisation hat. Ich mache dazu mal ein Issue auf.

**Comment by willuhn** [comment]
@phschoen Wir kommen hier ohne deine Hilfe nicht weiter.

**Comment by willuhn** [comment]
Ich habe ein neues Release 2.8.20 erstellt und lokal getestet. Hat alles funktioniert, soweit ich sehen konnte. Ich habe es unter https://github.com/openjverein/jverein/releases veröffentlicht. Im Jameica-Repository ist es aber noch nicht eingetragen. Das heisst, es wird noch nicht per Auto-Update zu den Usern ausgerollt. Bevor wir das machen: Könnt ihr das Release bitte bei euch auch mal testen? Insbesondere auch das Update einer existierenden 2.8.19 Installation.

Wenn ihr das OK liefert, würde ich mich drum kümmern, dass es ausgerollt wird. Ich würde das Jameica-Repository hierbei so einstellen, dass sowohl 2.8.19 als auch 2.8.20 verfügbar bleiben, damit User im Fehlerfall ein Downgrade machen können.

**Comment by phschoen** [comment]
> Ich finde es nicht gut, dass nur eine Person volle Berechtigungen auf die OpenJVerein Organisation hat. Ich mache dazu mal ein Issue auf.

genau der richtige weg :+1: 

@willuhn ich hab grade kein ant <1.10 daher kann ich es grade nicht bauen ohne auf java 8 umzustellen, daher danke. Der Build funktioniert, soweit ich es getestet habe, ebenfalls.

**Comment by NicoB77** [comment]
Hat bei mir auch funktioniert.

**Comment by willuhn** [comment]
Prima. Danke für die Tests. Ich habe das neue Release soeben ausgerollt ;)

https://openjverein.github.io/
