### ISSUE TITLE
Zurücktaste der Maus unterstützen

### ISSUE THREAD

**Issue by tolot27** [openjverein/jverein#495]
Ich fände es cool, wenn für den grünen Zurück-Pfeil neben der Alt+Links-Tastenkombination auch die Zurücktaste von Mäusen unterstützt werden würde. Es scheint jedoch noch nicht Java Standard zu sein. Für JavaFX ist es bei OpenJDK bereits implementiert.
Ansonsten muss man sich manuell wie unter https://stackoverflow.com/questions/7644842/how-can-i-use-the-back-and-forward-mouse-buttons-in-a-swing-application#7644995 beschrieben, behelfen.

**Comment by JohannMaierhofer** [comment]
Ich habe schon mal ein F5 und F6 bei Buttons entfernt weil es nur einen View gab der F Tasten bei Buttons benutzt hat.
Ich finde, wenn man eine Steuerung über Tasten einführt sollte man das konsequent überall machen und nicht punktuell.
Mir wäre ein einheitliches Verhalten der SW wichtig.

**Comment by tolot27** [comment]
Mir ist das auch wichtig und zwar unter konsequenter Nutzung der zur Verfügung stehenden Tasten bzw. so, wie sie mittlerweile üblicherweise von den OS/Browsern/Apps verwenden werden und wofür es auch usability guidelines gibt. 😄 
Allerdings glaube ich mittlerweile, dass dieses Feature in Jameica implementiert werden müsste und nicht in JVerein. Oder ist irgendwo das Verhalten von "Alt+Left" in JVerein codiert? Ich habe bisher nichts dazu gefunden.

**Comment by mbmueller** [comment]
> Allerdings glaube ich mittlerweile, dass dieses Feature in Jameica implementiert werden müsste und nicht in JVerein. Oder ist irgendwo das Verhalten von "Alt+Left" in JVerein codiert? Ich habe bisher nichts dazu gefunden

Theoretisch wäre es natürlich möglich, dass JVerein das implementiert, muss dann denke ich aber händisch für alle Views einzeln gemacht werden, was dann bei neuen Views oder Änderungen nicht mehr sicherstellt, dass es hier noch konsistent ist. Auch wäre das dann nicht mehr gegeben, wenn der Nutzer bspw. Hibiscus-Views verwendet. Daher würde ich da auch dafür plädieren, dass diese Funktionalität von Jameica übernommen werden muss.

**Comment by mbmueller** [comment]
Da es sich um ein Feature für Jameica handelt, schließe ich das Issue.
