### ISSUE TITLE
OpenJVerein mit IntelliJ IDEA

### ISSUE THREAD

**Issue by MSchmalzl** [openjverein/jverein#50]
Does someone already got the whole set of projects running in IntelliJ IDEA? 
I'd prefer using the IntelliJ IDE, cause I'm not the biggest fan of eclipse...

_Originally posted by @keep-hueggede in https://github.com/openjverein/jverein/issues/26#issuecomment-1425365538_

**Comment by mbmueller** [comment]
Ich habe es für mich fast zum laufen gebracht. Nur eine Library kann ich irgendwie noch nicht einbinden, aber da arbeite ich dran

**Comment by mbmueller** [comment]
Hatte es kurzzeitig am Laufen, jetzt behauptet er wieder er würde irgendeine Klasse nicht finden, die aber eigentlich da ist.... Bekomme das gerade auch nicht zum laufen. Werde vermutlich erstmal doch auf Eclipse umsteigen und nochmal neu klonen.

**Comment by mbmueller** [comment]
Um genau zu sein, bekomme ich diese Fehlermeldung:
`java.io.IOException: manifest G:\Coding\jameica-2.11.0-nightly.src\plugin.xml not readable`
@willuhn weißt du woher der Fehler kommen könnte?
