### ISSUE TITLE
"Ungültige IBAN" trotz korrekter IBAN

### ISSUE THREAD

**Issue by netmic10** [openjverein/jverein#509]
Zunächstmal vielen Dank an alle Entwickler für Eure Zeit und Engagement!

Bei einigen IBANs erhalte ich oben genannte Fehlermeldung, wenn ich Mitglieder-Daten speichern möchte, obwohl die IBAN korrekt ist. In meinem Fall betrifft das bisher drei IBANs der DKB AG (BLZ 12030000).

Seltsam auch: obwohl ich die IBAN-Prüfung in den Hibiscus-Einstellungen deaktiviert habe, werden die IBAN-Felder trotzdem geprüft und ich erhalte die Fehlermeldung. Demzufolge kann ich entsprechende Mitglieder-Daten mit diesen IBANs auch nicht anlegen / speichern.

Überhaupt seltsam: Ich habe die IBANs mit einem anderen IBAN-Tool geprüft, auch diese behaupten, die IBANs seihen nicht korrekt und nennen verschiedene mögliche Ursachen.

JVerein 2.8.23 (die vorherige Version hatte das gleiche Verhalten)

Mein Wunschverhalten: Prüfe die Mitglieder-Daten IBANs wenn in Hibiscus aktiviert, aber gib höchstens eine Warnung aus und erlaube das Speichern der Mitglieder-Daten trotzdem.

**Comment by netmic10** [comment]
@lenilsas Die IBAN kann von dem Hibiscus-Rechner nicht berechnet werden. Das hatte ich geprüft.

<img width="500" alt="IBAN-Rechner" src="https://github.com/user-attachments/assets/fa23852b-72b3-4cad-8c61-044214fe47c4">

Die IBAN ist aber korrekt. Ich habe Sie direkt aus der Sammellastschrift-Vorlage der Bank kopiert, so wie Sie auch vom Mitglied angegeben wurde. Die Sammellastschriften werden erfolgreich eingezogen.
Es muss wohl doch den Fall geben, dass Kontonummern sich nicht mit gängigen Tools in IBANs umrechnen bzw. prüfen lassen. Die Kontonummer ist 10-stellig, wie alle anderen auch.

Das Alternative Tool, mit dem ich die Kontonummern erfolglos geprüft habe, ist übrigens WISO Steuer. Vielleicht nutzt Buhl aber die gleiche Bibliothek wie Hibiscus... wer weiß.

**Comment by lenilsas** [comment]
@willuhn kannst du dir das mal anschauen, die Tests finden ja über die Hibiscus Funktion statt

**Comment by willuhn** [comment]
WISO nutzt nicht die selbe Bibliothek. Generell würde ich von der Umrechnung von Kontonummer/BLZ in IBAN Abstand nehmen. Das war nach Einführung der IBAN eine Zeit lang notwendig. Inzwischen gab es aber so viele Banken-Fusionen, sodass heute bei vielen IBANs die darin enthaltene BLZ gar nicht mehr zur tatsächlichen Bank passt.

Wenn auch andere Prüf-Tools (und WISO halte ich hier für eine ernst zu nehmende alternative Quelle), würde ich dir empfehlen, dich an den Kontoinhaber bzw. die DKB zu wenden und das dort klären lassen.

**Comment by netmic10** [comment]
Vielen Dank für Eure schnellen Antworten!
Ich muss mich entschuldigen! 😏 Habe eben nochmal ausgeschlafener auf die Sache geschaut und in allen drei Fällen IBAN-Ziffernfehler in den Listen gefunden, die ich per Import migrieren wollte. 🧐 Zweimal eine 0 mit einer anderen Ziffer verdreht und einmal musste es eine 8 statt einer 3 sein. Jetzt klappt alles. Sowas.

Ich spende Euch (Euren Projekten) einen Extra-Kaffee als hoffentlich kleine Entschädigung für die Verwirrung.
