### ISSUE TITLE
Berechtigung OpenJVerein Organisation

### ISSUE THREAD

**Issue by MSchmalzl** [openjverein/jverein#51]
Derzeit hat nur @phschoen die vollen Rechte an der OpenJVerein Organisation. Falls er also ausfällt -wollen wir natürlich nicht hoffen, haben wir ein Problem.

Ich wäre dafür das @willuhn ebenfalls mit den kompletten Berechtigungen ausgestattet wird.

**Comment by willuhn** [comment]
@phschoen Wir kommen hier ohne deine Hilfe nicht weiter.

**Comment by phschoen** [comment]
closed. @willuhn ist nun auch Owner 👍
