### ISSUE TITLE
Statistik Jahrgänge zählt alle Mitglieder doppelt wegen neuer Zeile "Ohne Datum"

### ISSUE THREAD

**Issue by nikopp** [openjverein/jverein#531]
Hallo!

Mit #385 wurden auch die Mitglieder ohne eingetragenes Geburtsdatum in die Statistik Jahrgänge aufgenommen.

Bei uns ist für alle Mitglieder ein Geburtsdatum eingetragen.

In der Zeile "Ohne Datum" werden alle Mitglieder nochmal gezählt.
Und in der Zeile "Summe" sind die Zahlen dann genau doppelt so hoch wie sie sein sollten:

![image](https://github.com/user-attachments/assets/d06568a7-cab2-4493-9816-b6104ede07a1)
Niko

**Comment by JohannMaierhofer** [comment]
@lenilsas @dippeal habt ihr da eine Idee? 
Als ich das gemacht hatte ging es. Es wurde an dem Export auch nichts geändert.
Im Debugger sehe ich, dass der Filter mitgl.addFilter("geburtsdatum is not null"); ignoriert wird. Da kommen jetzt auch Mitglieder bei denen das geburtsdatum in der DB null ist. Und beim Filter auf null erhält man auch alle.
Wie kann das sein?
