### ISSUE TITLE
Validation failed: must be a collaborator

### ISSUE THREAD

**Issue by dippeal** [openjverein/jverein#56]
Würdet ihr bitte das VinRud:feature/automatische-verbuchung-von-steuern als PR aufnehmen. Wenn ich es versuche erhalte ich die Meldung "Pull request creation failed. Validation failed: must be a collaborator" - eine Lösung habe ich nicht gefunden.

https://github.com/openjverein/jverein/compare/openjverein:master...VinRud:feature/automatische-verbuchung-von-steuern

**Comment by NicoB77** [comment]
Am Besten wäre es, wenn Du bei Dir einen Branch für den Pull-Request anlegst und dort VinRud:feature/automatische-verbuchung-von-steuern über einen PR importierst. Dann kannst Du auch nötige Änderungen machen (die Datei für das Datenbank-Update muss umbenannt werden).

**Comment by dippeal** [comment]
okay
