### ISSUE TITLE
Familienverband wird nicht angezeigt, falls Mitgliedschaft nicht im Tab dargestellt wird.

### ISSUE THREAD

**Issue by NicoB77** [openjverein/jverein#6]
Wenn die Option `Zeige Mitgliedschaft in Tab` abgewählt wird, werden die GUI-Felder zum Familienverband nicht mehr angezeigt, insbesondere kann der Zahler für die Beiträge nicht mehr gewählt werden. [Forum](https://jverein-forum.de/viewtopic.php?p=10470#p10470)

**Comment by phschoen** [comment]
closed by  #7
