### ISSUE TITLE
Layout der Spendenbescheinigung

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#70]
Ich verschicke die ausgedruckten Spendenbescheinigungen in Briefumschlägen mit Fenster. Leider passt in der eingebauten Bescheinigung der Name und Anschrift des Spenders nicht in das Fenster des Briefumschlages. Früher habe ich dann die Adressen separat ausgedruckt und zusätzlich in den Briefumschlag gegeben.
Es wäre schön wenn man die eingebaute Spendenbescheinigung (PDF) so ändern könnte, dass die Anschrift des Spenders in das Fenster eines Briefumschlages passt und dabei auch der Aussteller in kleiner Schrift im Fenster sichtbar ist (falls die Bescheinigung zurückkommen sollte). Dann kann man sie direkt so verschicken.
Ich habe das für mich einmal ausprobiert und im Code eine kleine Änderung gemacht indem ich die ersten zwei Blöcke vertauscht habe. Damit passt es, ginge vielleicht aber auch noch schöner.
Anbei meine Datei. Das Original stammt aus dem alten Projekt.
PS: Ich habe auch noch geändert, dass nicht alles fett gedruckt wird. Das braucht soviel unnötigen Toner beim drucken.
[SpendenbescheinigungPrintAction.zip](https://github.com/openjverein/jverein/files/13257079/SpendenbescheinigungPrintAction.zip)
.

**Comment by JohannMaierhofer** [comment]
PS: Habe dazu auch die folgende Datei geändert.
[Reporter.zip](https://github.com/openjverein/jverein/files/13257150/Reporter.zip)

**Comment by willuhn** [comment]
Danke, dass du die Änderung direkt selbst vorgenommen hast. Kannst du das aber bitte als Pull-Request einreichen? Dann kann die Änderung von den anderen Mitentwicklern geprüft und übernommen werden.

**Comment by dippeal** [comment]
PR https://github.com/openjverein/jverein/pull/74 erstellt.

**Comment by willuhn** [comment]
Hab mein Approve gegeben.

**Comment by NicoB77** [comment]
Das Layout der Bescheinigungen ist vom Finanzministerium [vorgegeben ](https://esth.bundesfinanzministerium.de/esth/2016/C-Anhaenge/Anhang-37/I/anhang-37-I.html), wobei es Spielraum zu geben scheint. Hast Du überprüft, ob Deine Änderungen damit vereinbar sind?

**Comment by JohannMaierhofer** [comment]
Ich habe mir die Regeln angesehen. Laut Punkt 2 darf ich wohl nicht die Textpassagen vertauschen. Laut Punkt 3 darf man aber die Adresse so anordnen dass sie als Anschriftfeld verwendet werden kann. Wenn ich nicht vertausche hat man aber den Absender nicht im Fenster. Das wäre auch nicht gut. 
Ich habe mir jetzt andere Bescheinigungen angeschaut. Diese benutzen die Reihenfolge aus dem Muster, haben aber zwischen dem Aussteller Feld und dem nächten Text Absatz zusätzlich die Adresse für das Brieffenster eingebaut inkl. des Absender in klein. Im Namenfeld steht dann Name und Anschrift in einer Zeile zusätzlich. 
Was meint ihr?
Ich könnte die Bescheinigung entsprechend anpassen.

**Comment by BT-11** [comment]
Ich bin auch Kassenwart und wir stellen Spendenbescheinigungen aus. Es gab früher keine so großen Vorgaben ab die Form und das Aussehen. Mittlerweile wird das aber sehr streng gehandhabt und wir haben schon einige Bescheinigungen neu in das offizielle und schlecht gestaltete spendenbescheinigungsformular vom Finanzamt eintragen müssen Punkt ich sehe da nicht die Möglichkeit gegeben eine Anschrift an der passenden Stelle einzutragen stattdessen wäre ich dafür einen extra weißes Blatt auszudrucken mit der Anschrift des Empfängers an der passenden Stelle und einem kurzen Danke schreiben. Einen einfachen richtigen StandardBrief eben mit Standard Danke.

**Comment by JohannMaierhofer** [comment]
Das scheint mir eine gute Idee. Die Adresse auf der zweiten Seite kann man man dann ja auch auf die Rückseite drucken. 
Die gesetzliche Regelung nach Punk 2 sagt ja, dass man auf der Rückseite auch Dankesschreiben unterbringen darf.
Ich werde das jetzt mal versuchen. Erstmals nur mit der Anschrift, bin ja kein erfahrener Programmierer.
Beim Dankesschreiben braucht man ja auch noch das GUI um den Text einzugeben.

**Comment by dippeal** [comment]
Wenn die neuen Dateien hier wieder hochgeladen werden kann ich den PR https://github.com/openjverein/jverein/pull/74 um einen commit erweitern.

**Comment by JohannMaierhofer** [comment]
Ich habe jetzt eine neue Seite mit der Anschrift eingefügt. Beim vorhandenen Text habe ich nur einige Fettschrift umgewandelt und etwas die Schriftgrößen angepasst. Das wirkt gefälliger.
[Reporter.zip](https://github.com/openjverein/jverein/files/13280516/Reporter.zip)
[SpendenbescheinigungPrintAction.zip](https://github.com/openjverein/jverein/files/13280518/SpendenbescheinigungPrintAction.zip)

**Comment by dippeal** [comment]
Neuer commit https://github.com/openjverein/jverein/pull/74/commits/1150e5c2d44dec5f074313b53da36b203ae768bd erstellt.

**Comment by MSchmalzl** [comment]
Ereledigt mit #74.
