### ISSUE TITLE
Kontonummer in Buchungsliste

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#71]
Wenn man mehrere Konten hat und im Fenster Buchungen kein spezielles Konto ausgewählt ist hat man die Buchungen aller Konten. Erzeugt man dann über den Button "PDF Einzelbuchungen" die Buchungsliste erhält man die Buchungen aller Konten.
Leider kann man nicht erkennen von welchem Konto die einzelnen Buchungen sind da nur die Auszug Nummer im Bericht vorkommt und nicht auch das Konto. Das ist in diesem Ausdruck aber dringend nötig.
Ich habe den Code angepasst und das Konto eingefügt mit Anpassung der Spaltenbreiten. Das Konto ist jetzt immer eingefügt. Natürlich könnte man evtl. abfragen (wenn das geht?) ob der Report nur für ein Konto oder mehre ist. Bei nur einem Konto bräuchte man die Kontonummer evtl. nicht.
[BuchungAuswertungPDF.zip](https://github.com/openjverein/jverein/files/13265466/BuchungAuswertungPDF.zip)

**Comment by willuhn** [comment]
Danke, dass du die Änderung direkt selbst vorgenommen hast. Kannst du das aber bitte als Pull-Request einreichen? Dann kann die Änderung von den anderen Mitentwicklern geprüft und übernommen werden.

**Comment by JohannMaierhofer** [comment]
Ich bin leider kein erfahrener Programmierer und kenne mich mit Git nicht aus. Da müsste ich erst lernen wie ich einen Pull Request erstellen kann. Ich glaube, so leicht ist das nicht.
Ich habe aus einer Anleitung mir eine Eclipse Umgebung aufgesetzt (noch aus dem alten Repository, Heiners Version). Da konnte ich meine Änderungen machen. In BuchungAuswertungPDF.java gab es im neuen Repository bereits eine Änderung in Zeile 81. Die habe ich jetzt auch gemacht und neu hochgeladen. Die Files in meinem anderen Request waren im neuen Repository noch nicht geändert und sollten darum direkt verwendbar sein.
Ich weiß jetzt nicht wie wir weiter verfahren sollen. Am einfachsten wäre es sicherlich wenn jemand aus eurem Team versucht die Datei zu übernehmen.
In kalten, schlechten Wintertagen werde ich zumindest das neue Repository in Eclipse aufsetzten und mich etwas mit Git beschäftigen. Dann kann ich versuchen auch Pull Requests zu erstellen. Momentan bin ich da etwas überfordert.

**Comment by dippeal** [comment]
Ich habe einen PR https://github.com/openjverein/jverein/pull/73 erstellt - bitte prüfen.

**Comment by willuhn** [comment]
Danke für das Erstellen des PR. Habe mein Approve gegeben.

**Comment by dippeal** [comment]
Wenn [JohannMaierhofer](https://github.com/JohannMaierhofer) als Mitglied aufgenommen wird, könnte er auch Codes reviews erstellen.

**Comment by MSchmalzl** [comment]
Erledigt mit #73.
