### ISSUE TITLE
Fehler SpendenbescheinigungAction

### ISSUE THREAD

**Issue by JohannMaierhofer** [openjverein/jverein#75]
Beim Testen von #70 ist mir ein Fehler aufgefallen. 
Wenn man in der Liste der Spendenbescheinigungen eine Bescheinigung doppelt clicked sollte die Bescheinigung in einem View dargestellt werden. Das passiert aber nicht und es kommt die Meldung "Kein Mitgliedskonto ausgewählt". 
Das gleiche passiert wenn man den Button "neu (manuell)" klicked. Hier sollte eine leere Bescheinigung im View angezeigt werden.
Ich habe das nach verfolgt und der Grund ist in den Zeilen 45..48 in der Datei SpendenbescheinigungAction.java. 
Diese Zeilen sind im Originalrepository nicht enthalten. Wenn ich sie auskommentiere funktioniert es wieder wie es eigentlich gewünscht ist.
Ich weiß jetzt nicht warum dieser Check eingefügt wurde, jedenfalls führt das zu dem beschriebenen Problem.

**Comment by dippeal** [comment]
Problem besteht seit openjverein Build 2.8.20. Siehe #20 und #21 und im Code [e0b2c87](https://github.com/openjverein/jverein/commit/e0b2c87da095810fef60682a80abf7bb1386489f#diff-eabd0fb48c55602602a1fb0721f89a124d9c579aabb3752c90c6052ccf116e79)

**Comment by JohannMaierhofer** [comment]
Also wenn ich mir den Code anschaue dann bearbeitet er mehrere mögliche Eingangsparameter und erlaubt auch NULL.
Falls man also eine Prüfung vorab einbaut sollte sie wie folgt aussehen (evtl. bessere Fehlermeldung):

if (!(context == null || context instanceof Spendenbescheinigung || context instanceof MitgliedskontoNode || context instanceof Mitglied))
{
    throw new ApplicationException("Falsches Element ausgewählt");
}

**Comment by dippeal** [comment]
> Also wenn ich mir den Code anschaue dann bearbeitet er mehrere mögliche Eingangsparameter und erlaubt auch NULL. Falls man also eine Prüfung vorab einbaut sollte sie wie folgt aussehen (evtl. bessere Fehlermeldung):
> 
> if (!(context == null || context instanceof Spendenbescheinigung || context instanceof MitgliedskontoNode || context instanceof Mitglied)) { throw new ApplicationException("Falsches Element ausgewählt"); }

Dein Code würde, meiner Meinung nach, nicht zum gewünschten Ergebnis führen. Habe einen PR https://github.com/openjverein/jverein/pull/76 erstellt und die Fehler korrigiert.

**Comment by JohannMaierhofer** [comment]
Ich bin immer noch der Meinung, dass mein Vorschlag stimmt. Ich habe deine Änderung ausprobiert und damit funktioniert der Button "manuell(neu)" in dem View der Spendenbescheinigungen nicht. Der Button übergibt "null" an die Funktion. Sie erstellt dann eine Lehre Spendenbescheinigung. Also sollte das auch erlaubt sein.

**Comment by JohannMaierhofer** [comment]
Natürlich könnte null auch bei einem Fehlerfall übergeben werden, was man dann damit nicht abfängt.
Eine ganz saubere Lösung wäre wohl beim Button neu(manuell) etwas anderes als nichts zu übergeben z.B. einen Text und den dann explizit zu akzeptieren. Damit bliebe die null ein Fehler.

**Comment by dippeal** [comment]
Wird die if Abfrage dann überhaupt benötigt? Es wird doch in den anschließenden Zeilen nach != null und dem instanceof geprüft.

**Comment by JohannMaierhofer** [comment]
Eigentlich ist die Abfrage nicht nötig.

**Comment by dippeal** [comment]
PR https://github.com/openjverein/jverein/pull/76 aktualisiert.
Wäre gut, wenn du der Organisation beitrittst (Beispiel https://github.com/openjverein/jverein/issues/64) und die Code-Anpassungen validieren könntest.
