### ISSUE TITLE
Ich würd gerne mithelfen

### ISSUE THREAD

**Issue by SchachtnerTh** [openjverein/jverein#8]
Hallo zusammen,

ich schreibe hier ein "Issue" rein, weil: "Erstellt ein Issue, dass ihr mitmachen wollt"
Ich habe zwar Null Erfahrung im Bereich der verteilten Software-Entwicklung, habe auch fast keine Erfahrung mit git oder github und habe auch nicht viel Zeit.
Aber ich würde dieses Projekt gerne mit voranbringen, Neues dazulernen und auch ein bisschen Zeit investieren wollen. Wenn ich also helfen kann, möchte ich das hiermit anbieten.

Viele Grüße
Tom

**Comment by phschoen** [comment]
ich habe dich mal hinzugefügt zum Team als Member :)

**Comment by phschoen** [comment]
Invitation expired. User did not accept this invite for 7 days
