### ISSUE TITLE
Teilnahme an GitHub Organisation

### ISSUE THREAD

**Issue by almereyda** [openjverein/jverein#84]
@dippeal hat in https://github.com/openjverein/jverein/discussions/80#discussioncomment-7649812 vorgeschlagen, dass ich mich in die Organisation mit aufnehmen lasse, damit ich leichter beitragen kann. Ich würde vor allem die Build Workflows im Blick behalten.

Einige der anderen Mitglieder könnten sich auch auf der Seite https://github.com/orgs/openjverein/people auf Public stellen, damit auch für Außenstehende zu sehen ist, dass hier mehr Leute mitwirken als nur @willuhn.

**Comment by willuhn** [comment]
Einladung ist soeben raus.
