### ISSUE TITLE
Mitmachen - Wie geht es weiter?

### ISSUE THREAD

**Issue by tobidope** [openjverein/jverein#9]
Ich hätte Interesse JVerein am Leben zu halten. Für mich wären die dringensten Sachen

- continous integration durch github actions ermöglichen
 Momentan wird soweit ich weiß nur lokal gebaut. Auch wenn kaum Tests vorhanden sind, sollte zumindest ein automatisierter build möglich sein
- lifecycle management ermöglichen
  Die per Hand eingestreuten jars wo möglich durch maven dependencies ablösen und aktualisieren
- ant durch maven oder gradle ersetzen
  ant macht man nur noch wenn man einen ganz schlimmen legacy build hat, den keiner mehr warten kann. Für maven und gradle wird man viel mehr Menschen mit Ahnung finden

Würde mich interessieren, wie der Rest es so sieht (Sofern es noch mehr gibt)

**Comment by phschoen** [comment]
du kannst gerne ein issue aufmachen für die jeweiligen Punkte als Improvment :+1: 
hinzugefügt habe ich dich auf jedenfall mal

**Comment by almereyda** [comment]
Die Lifecycle Management Fragen könnten in

- #19 

fortgeführt werden.
